force-app/main/default/objects/AML__c/AML__c.object-meta.xml
<CustomObject>
    <label>AML</label>
    <nameField>
        <displayFormat>AML-{000000}</displayFormat>
        <label>AML Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMLS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AML__c/fields/AML_Type__c.field-meta.xml
<CustomField>
    <fullName>AML_Type__c</fullName>
    <label>AML Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Conveyance__c.field-meta.xml
<CustomField>
    <fullName>Conveyance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Conveyance__c</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Inquiry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Inquiry</label>
    <referenceTo>pba__Request__c</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>AML Rejected</fullName>
            </value>
            <value>
                <fullName>KYC Pending</fullName>
            </value>
            <value>
                <fullName>KYC Submitted</fullName>
            </value>
            <value>
                <fullName>KYC Approved</fullName>
            </value>
            <value>
                <fullName>KYC Rejected</fullName>
            </value>
            <value>
                <fullName>KYC Completed</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>Document  Pending</fullName>
            </value>
            <value>
                <fullName>AML Complete</fullName>
            </value>
            <value>
                <fullName>TOB Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Conditional_Approved</fullName>
                <isActive>false</isActive>
                <label>Conditional Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Upload_Passport__c.field-meta.xml
<CustomField>
    <fullName>Upload_Passport__c</fullName>
    <label>Upload Passport?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agency</fullName>
                <label>3rd Party Agency</label>
            </value>
            <value>
                <fullName>Agency Client</fullName>
                <label>3rd Party Agency Client</label>
            </value>
            <value>
                <fullName>Agent</fullName>
                <label>3rd Party Agent</label>
            </value>
            <value>
                <fullName>Agents</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Property Manager</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>Referred Contact</fullName>
            </value>
            <value>
                <fullName>Search Agent</fullName>
            </value>
            <value>
                <fullName>Seller</fullName>
            </value>
            <value>
                <fullName>Solicitor</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Upload_Passport__c.field-meta.xml
<CustomField>
    <fullName>Upload_Passport__c</fullName>
    <label>Upload Passport?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conveyance__c/Conveyance__c.object-meta.xml
<CustomObject>
    <label>Sales Contract</label>
    <nameField>
        <displayFormat>{YY}{000}</displayFormat>
        <label>Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Conveyance__c/fields/Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Inquiry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inquiry</label>
    <referenceTo>pba__Request__c</referenceTo>
    <relationshipName>Conveyances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conveyance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Conveyance_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/Trigger_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger setting</label>
</CustomObject>

force-app/main/default/objects/Trigger_Setting__c/fields/Is_ContentVersion_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Is_ContentVersion_Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ContentVersion Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Conveyance_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
        <default>true</default>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>Contract Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Document Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Drafting</fullName>
    </customValue>
    <customValue>
        <fullName>Signing</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Executed</fullName>
    </customValue>
    <customValue>
        <fullName>NOC Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Exchanged</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Fall Through</fullName>
    </customValue>
    <customValue>
        <fullName>Settellment</fullName>
        <isActive>false</isActive>
        <label>Settellment</label>
    </customValue>
    <customValue>
        <fullName>Final Offer Letter</fullName>
        <isActive>false</isActive>
        <label>Final Offer Letter</label>
    </customValue>
    <customValue>
        <fullName>Valuation</fullName>
        <isActive>false</isActive>
        <label>Valuation</label>
    </customValue>
    <customValue>
        <fullName>Request MOS</fullName>
        <isActive>false</isActive>
        <label>Request MOS</label>
    </customValue>
    <masterLabel>Conveyance Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YES</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <label>N/A</label>
    </customValue>
    <masterLabel>Yes/No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestCopyAMLFilesToConveyance.cls
@isTest
private class TestCopyAMLFilesToConveyance {
    
    static testMethod void TestCopyAMLFilesToConveyance() {
        try{
            
            //Create Account
            List<Account> AccountList = new List<Account>();
            Account  AccountObj = new Account();
            AccountObj.Name ='test';
            AccountList.add(AccountObj);
            insert AccountList;
           // system.debug('acc='+acc);
            
            //Create Contact
            List<Contact> ContactList = new List<Contact>();
            Contact ContactObj = new Contact();
            ContactObj.LastName ='test1';
            ContactObj.ContactType__c = 'Buyer';	
            ContactList.add(ContactObj);
            insert ContactList;
            //system.debug('cont ='+cont);
            
            //Create Inquiry
            List<pba__Request__c> InquiryList = new List<pba__Request__c>();
            pba__Request__c InquiryObj = new pba__Request__c();
            InquiryObj.RecordTypeId	='0121t0000008UkHAAU';
            InquiryObj.InquiryType__c = 'Buyer';
            InquiryObj.pba__Bedrooms_pb_min__c = 4;
            InquiryObj.pba__Bedrooms_pb_max__c	 =4;
            InquiryObj.pba__ListingPrice_pb_min__c =5;
            InquiryObj.pba__ListingPrice_pb_max__c	=5;
            InquiryList.add(InquiryObj);
            insert InquiryList;
           // system.debug('inq='+inq);
            
            List<Trigger_Setting__c> SettingList = new List<Trigger_Setting__c>();
            Trigger_Setting__c settingObj = new Trigger_Setting__c();
            settingObj.Is_ContentVersion_Inactive__c = true;
            SettingList.add(settingObj);
            insert SettingList;
            
            //Create AML
            List<AML__c> AMLList = new List<AML__c>();
            AML__c AMLObj = new AML__c();
            AMLObj.Company__c = AccountObj.Id;
            AMLObj.Contact__c = ContactObj.Id;
            AMLObj.Inquiry__c = InquiryObj.Id;
            AMLObj.AML_Type__c = 'Corporate';
            AMLObj.Status__c = 'Draft';
            AMLObj.Role__c = 'Buyer';
            AMLObj.AML_Type__c = 'Individual';
            AMLObj.Upload_Passport__c = 'Yes';
            AMLList.add(AMLObj);
            insert AMLList;
           // system.debug('aml ='+aml);
           
            //Create a ContentVersion for passport
            
            ContentVersion ContentVer = new ContentVersion();
            ContentVer.Title = 'Passport';
            ContentVer.ContentUrl= 'test.com';
            insert ContentVer;
            
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument ];
            ContentDocumentLink contDoc = new ContentDocumentLink();
            contDoc.LinkedEntityId = AMLObj.id;
            contDoc.ShareType='V';
            contDoc.ContentDocumentId =[SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: ContentVer.Id].ContentDocumentId;
            contDoc.Visibility='AllUsers';
            insert contDoc;
            
            //Create a ContentVersion title KYC
            
            ContentVersion ContentVer1 = new ContentVersion();
            ContentVer1.Title = 'KYC';
            ContentVer1.ContentUrl= 'test.com';
            insert ContentVer1;
            List<ContentDocument> documents1 = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument ];
            
            ContentDocumentLink contDoc1 = new ContentDocumentLink();
            contDoc1.LinkedEntityId = AMLObj.id;
            contDoc1.ShareType='V';
            contDoc1.ContentDocumentId =[SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: ContentVer1.Id].ContentDocumentId;
            contDoc1.Visibility='AllUsers';
            insert contDoc1;
            
            //Create a ContentVersion title EID
            ContentVersion ContentVer2 = new ContentVersion();
            ContentVer2.Title = 'EID';
            ContentVer2.ContentUrl= 'test.com';
            insert ContentVer2;
            
            List<ContentDocument> documents2 = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument ];
            
            ContentDocumentLink contDoc2 = new ContentDocumentLink();
            contDoc2.LinkedEntityId = AMLObj.id;
            contDoc2.ShareType='V';
            contDoc2.ContentDocumentId =[SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: ContentVer2.Id].ContentDocumentId;
            contDoc2.Visibility='AllUsers';
            insert contDoc2;
            
            
            //Create a ContentVersion title VISA
            
            ContentVersion ContentVer3 = new ContentVersion();
            ContentVer3.Title = 'VISA';
            ContentVer3.ContentUrl= 'test.com';
            insert ContentVer3;
            
            List<ContentDocument> documents3 = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument ];
            
            ContentDocumentLink contDoc3 = new ContentDocumentLink();
            contDoc3.LinkedEntityId = AMLObj.id;
            contDoc3.ShareType='V';
            contDoc3.ContentDocumentId =[SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: ContentVer3.Id].ContentDocumentId;
            contDoc3.Visibility='AllUsers';
            insert contDoc3;
           
            
            //Create Convenyance  
            List<Conveyance__c> ConveyanceList = new List<Conveyance__c>();     
            Conveyance__c conveyanceObj = new Conveyance__c();
            conveyanceObj.Inquiry__c = InquiryObj.Id;
            conveyanceList.add(conveyanceObj);
            insert ConveyanceList;
            
            ContentVersion ContentVerA = new ContentVersion();
            ContentVerA.Title = 'Passport';
            ContentVerA.ContentUrl= 'test.com';
            insert ContentVerA;
            system.debug('ContentVerA'+ContentVerA);
            
            ContentDocumentLink contDocA1 = new ContentDocumentLink();
            contDocA1.LinkedEntityId = conveyanceObj.Id;
            contDocA1.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: ContentVerA.Id].ContentDocumentId;
            insert contDocA1;
            system.debug('contDocA1'+contDocA1);
            
            ContentVersion ContentVerB = new ContentVersion();
            ContentVerB.Title = 'KYC';
            ContentVerB.ContentUrl= 'test.com';
            insert ContentVerB;
            system.debug('ContentVerB'+ContentVerB);
            
            ContentDocumentLink contDocB1 = new ContentDocumentLink();
            contDocB1.LinkedEntityId = conveyanceObj.Id;
            contDocB1.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: ContentVerB.Id].ContentDocumentId;
            insert contDocB1;
            system.debug('contDocB1'+contDocB1);
            
            ContentVersion ContentVerC = new ContentVersion();
            ContentVerC.Title = 'EID';
            ContentVerC.ContentUrl= 'test.com';
            insert ContentVerC;
            system.debug('ContentVerC'+ContentVerC);
            
            ContentDocumentLink contDocC1 = new ContentDocumentLink();
            contDocC1.LinkedEntityId = conveyanceObj.Id;
            contDocC1.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: ContentVerC.Id].ContentDocumentId;
            insert contDocC1;
            system.debug('contDocC1'+contDocC1);
            
            ContentVersion ContentVerD = new ContentVersion();
            ContentVerD.Title = 'VISA';
            ContentVerD.ContentUrl= 'test.com';
            insert ContentVerD;
            system.debug('ContentVerD'+ContentVerD);
            
            ContentDocumentLink contDocD1 = new ContentDocumentLink();
            contDocD1.LinkedEntityId = conveyanceObj.Id;
            contDocD1.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: ContentVerD.Id].ContentDocumentId;
            insert contDocD1;
            system.debug('contDocD1'+contDocD1);
          
            
            Test.startTest();
            
            Database.update(contDoc);
            Test.stopTest();
            }catch(ListException e){
             System.debug('List exception fired');         
        }
    }    
}