force-app/main/default/objects/AML__c/AML__c.object-meta.xml
<CustomObject>
    <label>AML</label>
    <nameField>
        <displayFormat>AML-{000000}</displayFormat>
        <label>AML Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMLS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AML__c/fields/AML_Type__c.field-meta.xml
<CustomField>
    <fullName>AML_Type__c</fullName>
    <label>AML Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Inquiry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Inquiry</label>
    <referenceTo>pba__Request__c</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Sharing Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>AML Rejected</fullName>
            </value>
            <value>
                <fullName>KYC Pending</fullName>
            </value>
            <value>
                <fullName>KYC Submitted</fullName>
            </value>
            <value>
                <fullName>KYC Approved</fullName>
            </value>
            <value>
                <fullName>KYC Rejected</fullName>
            </value>
            <value>
                <fullName>KYC Completed</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>Document  Pending</fullName>
            </value>
            <value>
                <fullName>AML Complete</fullName>
            </value>
            <value>
                <fullName>TOB Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Conditional_Approved</fullName>
                <isActive>false</isActive>
                <label>Conditional Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Upload_Passport__c.field-meta.xml
<CustomField>
    <fullName>Upload_Passport__c</fullName>
    <label>Upload Passport?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/recordTypes/UK.recordType-meta.xml
<RecordType>
    <fullName>UK</fullName>
    <active>true</active>
    <label>UK</label>
</RecordType>

force-app/main/default/objects/Contact/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agency</fullName>
                <label>3rd Party Agency</label>
            </value>
            <value>
                <fullName>Agency Client</fullName>
                <label>3rd Party Agency Client</label>
            </value>
            <value>
                <fullName>Agent</fullName>
                <label>3rd Party Agent</label>
            </value>
            <value>
                <fullName>Agents</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Property Manager</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>Referred Contact</fullName>
            </value>
            <value>
                <fullName>Search Agent</fullName>
            </value>
            <value>
                <fullName>Seller</fullName>
            </value>
            <value>
                <fullName>Solicitor</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Secondary Regions (Sharing Rule)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UK Sotheby&apos;s International Realty</fullName>
            </value>
            <value>
                <fullName>Luxhabitat Sotheby&apos;s International Realty</fullName>
                <label>Dubai Sotheby&apos;s International Realty</label>
            </value>
            <value>
                <fullName>Saudi Arabia Sotheby&apos;s International Realty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sharing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Rule__c</fullName>
    <defaultValue>&quot;Private&quot;</defaultValue>
    <label>Sharing Rule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open to All Countries</fullName>
                <color>#B6E32E</color>
                <label>Open to All Countries</label>
            </value>
            <value>
                <fullName>Private</fullName>
                <color>#993399</color>
                <label>Private</label>
            </value>
            <value>
                <fullName>Exclusive Project UAE</fullName>
                <color>#663366</color>
                <label>Exclusive Project UAE</label>
            </value>
            <value>
                <fullName>UK Sothebys International Realty</fullName>
                <color>#F96FB7</color>
                <label>UK Sotheby&apos;s International Realty</label>
            </value>
            <value>
                <fullName>Saudi Arabia Sothebys International Realty</fullName>
                <color>#FF9900</color>
                <label>Saudi Arabia Sotheby&apos;s International Realty</label>
            </value>
            <value>
                <fullName>UAE Sotheby&apos;s International Realty</fullName>
                <color>#33CCFF</color>
                <label>UAE Sotheby&apos;s International Realty</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Upload_Passport__c.field-meta.xml
<CustomField>
    <fullName>Upload_Passport__c</fullName>
    <label>Upload Passport?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Sharing Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/New_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>UAE</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi</fullName>
    </customValue>
    <masterLabel>New Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>UAE</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YES</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <label>N/A</label>
    </customValue>
    <masterLabel>Yes/No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_triggerHandler_ContentDocLink.cls
@istest
public class Test_triggerHandler_ContentDocLink {
    
    @testSetup 
    public static void testData(){
        
    User objUser = [select Id, name, Region__c
    				from User 
                    where Region__c = 'UK' and isActive = true limit 1];
        System.runAs(objUser){
        //Create Account
        Account  AccountObj = new Account();
        AccountObj.Name ='test';
        insert AccountObj;
        
        //Create Contact
        Contact ContactObj = new Contact();
        ContactObj.LastName ='test1';
        ContactObj.ContactType__c = 'Buyer';	
        ContactObj.AccountId = AccountObj.Id;
        
        insert ContactObj;
        
        //Create Inquiry
        pba__Request__c InquiryObj = new pba__Request__c();
        InquiryObj.RecordTypeId	='0127T000000Gr33'; //0121t0000008UkHAAU
        InquiryObj.InquiryType__c = 'Buyer';
        InquiryObj.pba__Bedrooms_pb_min__c = 4;
        InquiryObj.pba__Bedrooms_pb_max__c	 =4;
        InquiryObj.pba__ListingPrice_pb_min__c =5;
        InquiryObj.pba__ListingPrice_pb_max__c	=5;
        InquiryObj.Sharing_Rule__c = 'UK Sotheby\'s International Realty';
        
        insert InquiryObj;
            
        AML__c AMLObj = new AML__c();
        AMLObj.Company__c = AccountObj.Id;
        AMLObj.Contact__c = ContactObj.Id;
        AMLObj.Inquiry__c = InquiryObj.Id;
        AMLObj.Status__c = 'TOB Pending';
        AMLObj.RecordTypeId = '0127T000000scUq';
        AMLObj.Role__c = 'Buyer';
        AMLObj.AML_Type__c = 'Individual';
        AMLObj.Upload_Passport__c = 'Yes';
        insert AMLObj;    
        /*
        AML__c AMLObj = new AML__c();
        AMLObj.Company__c = AccountObj.Id;
        AMLObj.Contact__c = ContactObj.Id;
        AMLObj.Inquiry__c = InquiryObj.Id;
        AMLObj.AML_Type__c = 'Individual';
        AMLObj.Status__c = 'Draft';
        AMLObj.Role__c = 'Buyer';
        AMLObj.AML_Type__c = 'Individual';
        AMLObj.Upload_Passport__c = 'Yes';
        insert AMLObj;
            */
        } 
     // AMLObj.Status__c = 'Compliance Review';
     // update AMLObj;
        /*
        AMLObj.Status__c = 'Compliance Review';
        update AMLObj;
        */
        /*
        AMLObj.Status__c = 'Document Pending';
        update AMLObj;
        */
        
    }
    
    @istest
    public static void test1(){
        Account  AccountObj = [select id from Account];
        Contact  ContactObj = [select id from Contact];
        pba__Request__c  InquiryObj = [select id from pba__Request__c];
        
        AML__c  AMLObj = [select id from AML__c];
        /*
        AML__c AMLObj = new AML__c();
        AMLObj.Company__c = AccountObj.Id;
        AMLObj.Contact__c = ContactObj.Id;
        AMLObj.Inquiry__c = InquiryObj.Id;
        AMLObj.Status__c = 'TOB Pending';
        AMLObj.RecordTypeId = '0127T000000scUq';
        AMLObj.Role__c = 'Buyer';
        AMLObj.AML_Type__c = 'Individual';
        AMLObj.Upload_Passport__c = 'Yes';
        insert AMLObj;
        */
        
        ContentVersion ContentVer = new ContentVersion();
        ContentVer.Title = 'Passport';
        ContentVer.ContentUrl= 'test.com';
        insert ContentVer;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument ];
        ContentDocumentLink contDoc = new ContentDocumentLink();
        contDoc.LinkedEntityId = AMLObj.id;
        contDoc.ShareType='V';
        contDoc.ContentDocumentId =[SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: ContentVer.Id].ContentDocumentId;
        contDoc.Visibility='AllUsers';
        insert contDoc;   
        
    }
    
    @istest
    public static void test2(){
        triggerHandler_ContentDocLink.fakeMethod();
    }
}