force-app/main/default/objects/AML__c/AML__c.object-meta.xml
<CustomObject>
    <label>AML</label>
    <nameField>
        <displayFormat>AML-{000000}</displayFormat>
        <label>AML Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMLS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AML__c/fields/AML_Type__c.field-meta.xml
<CustomField>
    <fullName>AML_Type__c</fullName>
    <label>AML Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Closing__c.field-meta.xml
<CustomField>
    <fullName>Closing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closing</label>
    <referenceTo>pba__Closing__c</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Inquiry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Inquiry</label>
    <referenceTo>pba__Request__c</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing</label>
    <referenceTo>pba__Listing__c</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer</label>
    <referenceTo>pba__Offer__c</referenceTo>
    <relationshipLabel>AMLS</relationshipLabel>
    <relationshipName>AMLS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AML__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Sharing Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <inlineHelpText>Choose Self If its for Primary Contact else choose other values</inlineHelpText>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Relationship</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <label>Resident</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CIF__c/CIF__c.object-meta.xml
<CustomObject>
    <label>CIF</label>
    <nameField>
        <displayFormat>CIF-{00000}</displayFormat>
        <label>CIF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIF</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CIF__c/fields/Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Inquiry__c</fullName>
    <formula>IF (NOT(ISBLANK(Requested_Inquiry_Id__c)),HYPERLINK(&quot;/&quot; &amp;  Requested_Inquiry_Id__c ,  NAME_OF_THE_OWNER__c ),&apos;NA&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inquiry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIF__c/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing</label>
    <referenceTo>pba__Listing__c</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>New_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CIF__c/fields/Resident__c.field-meta.xml
<CustomField>
    <fullName>Resident__c</fullName>
    <label>Resident</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CIF</label>
    <referenceTo>CIF__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agency</fullName>
                <label>3rd Party Agency</label>
            </value>
            <value>
                <fullName>Agency Client</fullName>
                <label>3rd Party Agency Client</label>
            </value>
            <value>
                <fullName>Agent</fullName>
                <label>3rd Party Agent</label>
            </value>
            <value>
                <fullName>Agents</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Property Manager</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>Referred Contact</fullName>
            </value>
            <value>
                <fullName>Search Agent</fullName>
            </value>
            <value>
                <fullName>Seller</fullName>
            </value>
            <value>
                <fullName>Solicitor</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Do_Not_Run_Automation__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Run_Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Run Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/gsir_sender_recipient__c.field-meta.xml
<CustomField>
    <fullName>gsir_sender_recipient__c</fullName>
    <label>Sender Recipient</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pba__CompanyName__c.field-meta.xml
<CustomField>
    <fullName>pba__CompanyName__c</fullName>
    <label>Company</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Secondary Regions (Sharing Rule)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UK Sotheby&apos;s International Realty</fullName>
            </value>
            <value>
                <fullName>Luxhabitat Sotheby&apos;s International Realty</fullName>
                <label>Dubai Sotheby&apos;s International Realty</label>
            </value>
            <value>
                <fullName>Saudi Arabia Sotheby&apos;s International Realty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Relationship</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Migrated</fullName>
                <label>Existing Contact</label>
            </value>
            <value>
                <fullName>New_Lead</fullName>
                <label>New Contact</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/New_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>UAE</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi</fullName>
    </customValue>
    <masterLabel>New Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Relationship.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Self</fullName>
    </customValue>
    <customValue>
        <fullName>Wife</fullName>
    </customValue>
    <customValue>
        <fullName>Husband</fullName>
    </customValue>
    <customValue>
        <fullName>Father</fullName>
    </customValue>
    <customValue>
        <fullName>Mother</fullName>
    </customValue>
    <customValue>
        <fullName>Son</fullName>
    </customValue>
    <customValue>
        <fullName>Daughter</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Cousin</fullName>
    </customValue>
    <customValue>
        <fullName>Grandmother</fullName>
    </customValue>
    <customValue>
        <fullName>Grandfather</fullName>
    </customValue>
    <customValue>
        <fullName>Grandson</fullName>
    </customValue>
    <customValue>
        <fullName>Granddaughter</fullName>
    </customValue>
    <customValue>
        <fullName>Grandchild</fullName>
    </customValue>
    <customValue>
        <fullName>Aunt</fullName>
    </customValue>
    <customValue>
        <fullName>Uncle</fullName>
    </customValue>
    <customValue>
        <fullName>Employee</fullName>
    </customValue>
    <customValue>
        <fullName>Shareholder</fullName>
    </customValue>
    <customValue>
        <fullName>Friend</fullName>
    </customValue>
    <customValue>
        <fullName>Trust - Seller</fullName>
    </customValue>
    <customValue>
        <fullName>Trust - Trustee</fullName>
    </customValue>
    <customValue>
        <fullName>Trust - Benefeciaries</fullName>
    </customValue>
    <customValue>
        <fullName>Company - Beneficial Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Program Manager</fullName>
        <isActive>false</isActive>
        <label>Program Manager</label>
    </customValue>
    <customValue>
        <fullName>Residential Manager</fullName>
        <isActive>false</isActive>
        <label>Residential Manager</label>
    </customValue>
    <customValue>
        <fullName>DDS Case Manager</fullName>
        <isActive>false</isActive>
        <label>DDS Case Manager</label>
    </customValue>
    <customValue>
        <fullName>Spouse</fullName>
        <isActive>false</isActive>
        <label>Spouse</label>
    </customValue>
    <customValue>
        <fullName>Employer</fullName>
        <isActive>false</isActive>
        <label>Employer</label>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <isActive>false</isActive>
        <label>Staff</label>
    </customValue>
    <customValue>
        <fullName>Child</fullName>
        <isActive>false</isActive>
        <label>Child</label>
    </customValue>
    <masterLabel>Relationship</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YES</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <label>N/A</label>
    </customValue>
    <masterLabel>Yes/No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AMLFileHandlerTest.cls
@isTest
public class AMLFileHandlerTest {   
    @isTest(SeeAllData = True)
    static void testContentDocumentInsertion() {
        // Create a test ContentVersion record
        ContentVersion contentVersion = new ContentVersion(Title = 'Test Content',
                                                           PathOnClient = 'TestPathOnClient',
                                                           VersionData = Blob.valueOf('Test Content Data'));
        insert contentVersion;
        
        // Query for the ContentDocumentId using ContentVersion
        ContentVersion queriedContentVersion = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id LIMIT 1];
        
        // Use the obtained ContentDocumentId
        Id contentDocumentId = queriedContentVersion.ContentDocumentId; 
        
    /*    system.debug('error------------------ ');
        //Create TEst Contact Record
        Contact ContactRecord = new Contact(LastName = 'TestContactRecord',
                                           gsir_sender_recipient__c = Null,
                                           	Do_Not_Run_Automation__c = True,
                                           ContactType__c = 'Agency',
                                            pba__CompanyName__c = 'N/A',
                                           Region__c = Null,
                                           Stage__c = Null,    
                                           	CIF__c = Null); 
        insert ContactRecord; 
        
        system.debug('error3 '+ContactRecord);
        
        
        // Create test pba__Closing__c record
        pba__Closing__c closingRecord = new pba__Closing__c(Client_Type__c = 'Individual',
                                                            AML_Rating__c = Null,
                                                            Contract_Generating_User__c = Null,
                                                            Closing_Status__c = 'Open',
                                                            TargetClosingDate__c = Date.today(),
                                                            Accounted_Date__c = Date.today(),
                                                            gsir_closing_broker_split_amount__c = 0);
        insert closingRecord;
        system.debug('Closing Inserted Sussesfully>>> '+closingRecord);
                     
        // Create test pba__Listing__c record
        pba__Listing__c listingRecord = new pba__Listing__c(Name = 'TestListingRecord',
                                                           pba__ListingType__c= 'none',
                                                            External_Listing__c = True,
                                                            	gsir_form_a_expiry__c = Null,
                                                            pba__Status__c = 'none',
                                                            CurrencyIsoCode = 'GBP'                                                           
                                                           );        
        insert listingRecord;
        system.debug('Listing Inserted Sussesfully>>> '+listingRecord);
        
      
                       
        // Create test AML__c record related to the ContentDocument
        AML__c amlRecord = new AML__c(Inquiry__c = Null,
                                      Listing__c = listingRecord.Id,
                                      Closing__c = closingRecord.Id,
                                     // Contact__c = '0037E0000182yPpQAI',//'0037E0000182yPpQAI', '0037T00000PsLEiQAN'
                                      Contact__c = con.Id ,
                                      Offer__c = Null,                                      
                                      Relationship_Type__c = 'Self',
                                      Resident__c = 'YES',
                                      AML_Type__c = 'Corporate',
                                      Role__c = 'Seller');        
        insert amlRecord; 
        system.debug('AML Inserted Sussesfully>>> '+amlRecord);

        */
        AML__c acc = [Select Id from  AML__c Where Listing__c != Null AND Closing__c != Null Limit 1 ];
        
        // Create test ContentDocumentLink record related to AML
        ContentDocumentLink contentDocumentLink = new ContentDocumentLink(ContentDocumentId = contentDocumentId,
                                                                          LinkedEntityId = acc.Id,
                                                                          ShareType = 'I',
                                                                          Visibility = 'AllUsers');
        
        // Call the AMLFileHandler method
        Test.startTest();
        insert contentDocumentLink;
        Test.stopTest();
        
   /*     // Query for created ContentDocumentLinks
       List<ContentDocumentLink> createdContentDocumentListingLinks = [SELECT Id, LinkedEntityId,ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :listingRecord.Id];
       List<ContentDocumentLink> createdContentDocumentClosingLinks = [SELECT Id, LinkedEntityId,ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :closingRecord.Id];
        // Verify the expected behavior listing
        System.assertEquals(1, createdContentDocumentListingLinks.size(), 'Incorrect number of createdContentDocumentListingLinks created.');
        System.assertEquals(contentDocumentId, createdContentDocumentListingLinks[0].ContentDocumentId, 'Incorrect ContentDocumentId in createdContentDocumentListingLinks.');
        System.assertEquals(listingRecord.Id, createdContentDocumentListingLinks[0].LinkedEntityId, 'Incorrect LinkedEntityId in createdContentDocumentListingLinks.');
        // Verify the expected behavior Closing
        System.assertEquals(1, createdContentDocumentClosingLinks.size(), 'Incorrect number of createdContentDocumentClosingLinks created.');
       System.assertEquals(contentDocumentId, createdContentDocumentClosingLinks[0].ContentDocumentId, 'Incorrect ContentDocumentId in createdContentDocumentClosingLinks.');
       System.assertEquals(closingRecord.Id, createdContentDocumentClosingLinks[0].LinkedEntityId, 'Incorrect LinkedEntityId in createdContentDocumentClosingLinks.');
  */ 
}
}