force-app/main/default/objects/os_Project__c/os_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/os_Project__c/fields/os_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>os_Project_Name__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/os_Project__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OS_Property__c/OS_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OS_Property__c/fields/External_Area_Sq_ft__c.field-meta.xml
<CustomField>
    <fullName>External_Area_Sq_ft__c</fullName>
    <label>External Area Sq.ft.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OS_Property__c/fields/Internal_Area_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Internal_Area_Sq_Ft__c</fullName>
    <formula>os_Total_Area__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Area Sq.Ft.</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OS_Property__c/fields/os_No_of_Beds__c.field-meta.xml
<CustomField>
    <fullName>os_No_of_Beds__c</fullName>
    <label>No of Beds</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1BR</fullName>
            </value>
            <value>
                <fullName>2BR</fullName>
            </value>
            <value>
                <fullName>3BR</fullName>
            </value>
            <value>
                <fullName>4BR</fullName>
            </value>
            <value>
                <fullName>5BR</fullName>
            </value>
            <value>
                <fullName>6BR</fullName>
            </value>
            <value>
                <fullName>Garden Unit Duplex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OS_Property__c/fields/os_Project__c.field-meta.xml
<CustomField>
    <fullName>os_Project__c</fullName>
    <label>Project</label>
    <referenceTo>os_Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OS_Property__c/fields/os_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>os_Project_Name__c</fullName>
    <formula>os_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OS_Property__c/fields/os_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>os_Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OS_Property__c/fields/os_Status__c.field-meta.xml
<CustomField>
    <fullName>os_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Red Listed Review</fullName>
            </value>
            <value>
                <fullName>Red Listed</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OS_Property__c/fields/os_Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>os_Unit_Number__c</fullName>
    <label>Unit Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OS_Property__c/fields/os_View__c.field-meta.xml
<CustomField>
    <fullName>os_View__c</fullName>
    <label>View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marina</fullName>
            </value>
            <value>
                <fullName>Harbor</fullName>
            </value>
            <value>
                <fullName>City</fullName>
            </value>
            <value>
                <fullName>Golf Course</fullName>
            </value>
            <value>
                <fullName>Park</fullName>
            </value>
            <value>
                <fullName>Pool</fullName>
            </value>
            <value>
                <fullName>Courtyard</fullName>
            </value>
            <value>
                <fullName>Landscape</fullName>
            </value>
            <value>
                <fullName>Mountain</fullName>
            </value>
            <value>
                <fullName>Sheikh Zayed Road/Zaabeel Park</fullName>
            </value>
            <value>
                <fullName>Sheikh Zayed Road/Downtown</fullName>
            </value>
            <value>
                <fullName>Ocean/Community</fullName>
            </value>
            <value>
                <fullName>Zaabeel Park/Dubai Frame</fullName>
            </value>
            <value>
                <fullName>Tower 2/Community</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf</fullName>
            </value>
            <value>
                <fullName>DIFC / Burj Khalifa</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf &amp; Burj Khalifa</fullName>
            </value>
            <value>
                <fullName>Zaabeel &amp; DIFC / Burj Khalifa</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf &amp; The Dubai Frame</fullName>
            </value>
            <value>
                <fullName>The Dubai Frame &amp; Zaabeel View</fullName>
            </value>
            <value>
                <fullName>The Dubai Frame</fullName>
            </value>
            <value>
                <fullName>Sea</fullName>
            </value>
            <value>
                <fullName>Ocean</fullName>
            </value>
            <value>
                <fullName>Zaabeel</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf / The Dubai Frame</fullName>
            </value>
            <value>
                <fullName>DIFC Burj Khalifa</fullName>
            </value>
            <value>
                <fullName>Zaabeel / DIFC Burj Khalifa</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf / DIFC Burj Khalifa</fullName>
            </value>
            <value>
                <fullName>The Dubai Frame / Zaabeel</fullName>
            </value>
            <value>
                <fullName>Ocean View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OS_Property__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OS_Property__c/fields/Total_Area_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Total_Area_Sq_Ft__c</fullName>
    <formula>os_Total_Area__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Area Sq.Ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PropertyController.cls
public with sharing class PropertyController {
    
    @AuraEnabled(cacheable=true)
    public static List<OS_Property__c> getProperties() {
         List<OS_Property__c> units = [
        SELECT Id, os_Project_Name__c, os_Unit_Number__c, os_No_of_Beds__c, os_Sales_Price__c,Name,
               os_View__c, os_Tower__c, os_Status__c,Total_Area_Sq_ft__c,External_Area_Sq_ft__c,Internal_Area_Sq_ft__c
        FROM OS_Property__c
    ];
     System.debug('Fetched units: ' + units);
    return units;
    }
    @AuraEnabled(cacheable=true)
    public static List<os_Project__c> getProjects() {
        return [SELECT Id, Name FROM os_Project__c];
    }
    @AuraEnabled(cacheable=true)
    public static List<ComboOption> getPicklistValues(String objectApiName, String fieldApiName) {
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Schema.SObjectType sobjType = gd.get(objectApiName);
        Schema.DescribeSObjectResult describeSObjectResult = sobjType.getDescribe();
        Schema.DescribeFieldResult fieldResult = describeSObjectResult.fields.getMap().get(fieldApiName).getDescribe();

        List<ComboOption> options = new List<ComboOption>();
        for (Schema.PicklistEntry pe : fieldResult.getPicklistValues()) {
            options.add(new ComboOption(pe.getLabel(), pe.getValue()));
        }
        return options;
    }

    public class ComboOption {
        @AuraEnabled public String label {get; set;}
        @AuraEnabled public String value {get; set;}

        public ComboOption(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<Payment_Plan__c> getPaymentPlans() {
        return [SELECT Id, Name FROM Payment_Plan__c];
    }
}