force-app/main/default/objects/CD_Activity__c/CD_Activity__c.object-meta.xml
<CustomObject>
    <label>CD Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activitys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Activity__c/fields/CD_Activity__c.field-meta.xml
<CustomField>
    <fullName>CD_Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Payment Returned</fullName>
            </value>
            <value>
                <fullName>Reservation Signed by Client</fullName>
            </value>
            <value>
                <fullName>Signed Reservation Submitted to Developer .</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Activity__c/fields/CD_Index_No__c.field-meta.xml
<CustomField>
    <fullName>CD_Index_No__c</fullName>
    <label>Index No</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CD_Activity__c/fields/CD_Payment__c.field-meta.xml
<CustomField>
    <fullName>CD_Payment__c</fullName>
    <label>Payment</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Activity__c/fields/CD_Property__c.field-meta.xml
<CustomField>
    <fullName>CD_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>CD_Property__c</referenceTo>
    <relationshipName>Activitys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Activity__c/fields/CD_Receipt_Issued__c.field-meta.xml
<CustomField>
    <fullName>CD_Receipt_Issued__c</fullName>
    <label>Receipt Issued</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Activity__c/recordTypes/CD_Document.recordType-meta.xml
<RecordType>
    <fullName>CD_Document</fullName>
    <active>true</active>
    <label>Document</label>
</RecordType>

force-app/main/default/objects/CD_Activity__c/recordTypes/CD_Payment.recordType-meta.xml
<RecordType>
    <fullName>CD_Payment</fullName>
    <active>true</active>
    <label>Payment</label>
</RecordType>

force-app/main/default/objects/CD_Approval_Request__c/CD_Approval_Request__c.object-meta.xml
<CustomObject>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>CD_Agent_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>CD_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Requests_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Blocking_Comments__c.field-meta.xml
<CustomField>
    <fullName>CD_Blocking_Comments__c</fullName>
    <label>Blocking Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>CD_Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <formula>Property__r.CD_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Status__c.field-meta.xml
<CustomField>
    <fullName>CD_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>CD_Property__c</referenceTo>
    <relationshipLabel>Approval Requests</relationshipLabel>
    <relationshipName>Approval_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Project__c/CD_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/CD_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/fields/CD_Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>CD_Agent_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Name Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Unit (Agent Name Contact)</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>CD_Approver_Name__c</fullName>
    <formula>CD_Approver__r.FirstName+ &apos; &apos; +CD_Approver__r.LastName</formula>
    <label>Approver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Blocking_Comments__c.field-meta.xml
<CustomField>
    <fullName>CD_Blocking_Comments__c</fullName>
    <label>Blocking Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_isblocked__c.field-meta.xml
<CustomField>
    <fullName>CD_isblocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isblocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <label>Project</label>
    <referenceTo>CD_Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>CD_Unit_Number__c</fullName>
    <label>Unit Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/gsir_company__c.field-meta.xml
<CustomField>
    <fullName>gsir_company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gulf Sotheby&apos;s</fullName>
            </value>
            <value>
                <fullName>Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Clark &amp; Scott</fullName>
                <isActive>false</isActive>
                <label>Clark &amp; Scott</label>
            </value>
            <value>
                <fullName>External Brokers</fullName>
                <isActive>false</isActive>
                <label>External Brokers</label>
            </value>
            <value>
                <fullName>Internal Brokers</fullName>
                <isActive>false</isActive>
                <label>Internal Brokers</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/test_activityCreationCntrlr.cls
@istest
public class test_activityCreationCntrlr {
	
     @TestSetup
    static void SetupMethod(){
        
        
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        
        String orgId = UserInfo.getOrganizationId(); 
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId = Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName = orgId+dateString+RandomId; 
        User uu = new User(firstname = 'Benedict',  
                           lastName = 'Texeira', 
                           email = 'vijay@gmail.com', 
                           Username = 'Texeira@sfdc.dev', 
                           EmailEncodingKey = 'ISO-8859-1', 
                           Alias = uniqueName.substring(18, 23), 
                           TimeZoneSidKey = 'America/Los_Angeles', 
                           LocaleSidKey = 'en_US', 
                           LanguageLocaleKey = 'en_US', 
                           gsir_company__c= 'Gulf Sotheby\'s',
                           ProfileId = pf.Id
                          ); 
        insert uu;
    }
    
    @istest
    public static void test_createActivities()
    {
        
         User user1 = [SELECT Id,Email FROM User WHERE UserName = 'Texeira@sfdc.dev'];
        
        date expdate = system.today() +1;
        
         CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project1';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name = 'Test property1';
        prop.CD_Project__c = proj.id;
        prop.CD_isblocked__c = true;
        prop.CD_Unit_Number__c = 'Test Unit Number';
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        id recotdtypeIdVal=Schema.SObjectType.CD_Activity__c.getRecordTypeInfosByDeveloperName().get('CD_Payment').getRecordTypeId();
        CD_Approval_Request__c aprReq = new CD_Approval_Request__c();
        aprReq.CD_Expiry_Date__c = expdate;
        aprReq.CD_Blocking_Comments__c = 'test comment1';
        aprReq.CD_Status__c = 'Pending';
        aprReq.Property__c = prop.Id;
        aprReq.CD_Approver_Name__c = user1.Id;
        aprReq.CD_Agent_Name__c = user1.Id;
        
        insert aprReq;
        
        CD_Activity__c testAct = new CD_Activity__c();
        testAct.Name = 'Test activity';
        testAct.CD_Payment__c ='test payment';
        testAct.CD_Receipt_Issued__c ='Yes';
       //  testAct.CD_Property__c =  prop.Id;
        //    testAct.RecordTypeId = recotdtypeIdVal;
        list<CD_Activity__c> actList = new list<CD_Activity__c>();
        actList.add(testAct);
        
         id recotdtypeIdVal2=Schema.SObjectType.CD_Activity__c.getRecordTypeInfosByDeveloperName().get('CD_Document').getRecordTypeId();
         CD_Activity__c testAct2 = new CD_Activity__c();
        testAct2.Name = 'Test activity';
       // testAct.CD_Payment__c ='test payment';
       // testAct.CD_Receipt_Issued__c ='Yes';
        // testAct2.CD_Property__c =  prop.Id;
         //   testAct2.RecordTypeId = recotdtypeIdVal2;
        list<CD_Activity__c> actList2 = new list<CD_Activity__c>();
        actList2.add(testAct2);
     //   string base64 ='[{0,testbase64value},{1,testValue}]';
       // string filname = '[{0,Test file.pdf},{1,testvalue2}]';
       string base64 ='{"0":"testBase64"}';
        string filname = '{"0":"MicrosoftTeams-image.png"}';
        // insert testAct;
       // activityCreationCntrlr.getActivities(prop.id);
        activityCreationCntrlr.createActivities(actList,prop.id);
         activityCreationCntrlr.createDocumentActivities(actList2,prop.id);
        
    }
    @istest
    public static void test_createDocswithFIles()
    {
          User user1 = [SELECT Id,Email FROM User WHERE UserName = 'Texeira@sfdc.dev'];
        
        date expdate = system.today() +1;
         CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project1';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name = 'Test property1';
        prop.CD_Project__c = proj.id;
        prop.CD_isblocked__c = true;
        prop.CD_Unit_Number__c = 'Test Unit Number';
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        id recotdtypeIdVal=Schema.SObjectType.CD_Activity__c.getRecordTypeInfosByDeveloperName().get('CD_Payment').getRecordTypeId();
        CD_Approval_Request__c aprReq = new CD_Approval_Request__c();
        aprReq.CD_Expiry_Date__c = expdate;
        aprReq.CD_Blocking_Comments__c = 'test comment1';
        aprReq.CD_Status__c = 'Pending';
        aprReq.Property__c = prop.Id;
        aprReq.CD_Approver_Name__c = user1.Id;
        aprReq.CD_Agent_Name__c = user1.Id;
        
        insert aprReq;
        
        CD_Activity__c testAct = new CD_Activity__c();
        testAct.Name = 'Test activity';
        testAct.CD_Payment__c ='test payment';
        testAct.CD_Receipt_Issued__c ='Yes';
       //  testAct.CD_Property__c =  prop.Id;
        //    testAct.RecordTypeId = recotdtypeIdVal;
        list<CD_Activity__c> actList = new list<CD_Activity__c>();
        actList.add(testAct);
        
         id recotdtypeIdVal2=Schema.SObjectType.CD_Activity__c.getRecordTypeInfosByDeveloperName().get('CD_Document').getRecordTypeId();
         CD_Activity__c testAct2 = new CD_Activity__c();
        testAct2.Name = 'Test activity';
        testAct.CD_Payment__c ='test payment';
        testAct.CD_Receipt_Issued__c ='Yes';
         testAct2.CD_Property__c =  prop.Id;
        testAct2.CD_Index_No__c =0;
            testAct2.RecordTypeId = recotdtypeIdVal2;
        list<CD_Activity__c> actList2 = new list<CD_Activity__c>();
        actList2.add(testAct2);
         ContentVersion content=new ContentVersion(); 
        content.Title='Header_Picture1'; 
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        content.origin = 'H';
        insert content;
      /*  ContentDocumentLink contentlink=new ContentDocumentLink();
        //contentlink.LinkedEntityId= testAct2.id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers';
      contentlink.LinkedEntityId = [select id from CD_Activity__c limit 1].Id;
          insert contentlink; */
      // string base64 ='{"0":"\''+content.id +'\'"}'; 
        string base64 = '{"0": "0681q000005vbldAAA"}';
           //  \'' +getProjectName+'\''
        string filname = '{"0":"MicrosoftTeams-image.png"}';
		activityCreationCntrlr.createActivitiesWithFiles(actList2,prop.id,base64);
    }
    
    @istest
    public static void test_getActiities()
    {
         User user1 = [SELECT Id,Email FROM User WHERE UserName = 'Texeira@sfdc.dev'];
        
        date expdate = system.today() +1;
        
         CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project1';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name = 'Test property1';
        prop.CD_Project__c = proj.id;
        prop.CD_isblocked__c = true;
        prop.CD_Unit_Number__c = 'Test Unit Number';
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        id recotdtypeIdVal=Schema.SObjectType.CD_Activity__c.getRecordTypeInfosByDeveloperName().get('CD_Payment').getRecordTypeId();
        CD_Approval_Request__c aprReq = new CD_Approval_Request__c();
        aprReq.CD_Expiry_Date__c = expdate;
        aprReq.CD_Blocking_Comments__c = 'test comment1';
        aprReq.CD_Status__c = 'Pending';
        aprReq.Property__c = prop.Id;
        aprReq.CD_Approver_Name__c = user1.Id;
        aprReq.CD_Agent_Name__c = user1.Id;
        
        insert aprReq;
        
        CD_Activity__c testAct = new CD_Activity__c();
        testAct.Name = 'Test activity';
        testAct.CD_Payment__c ='test payment';
        testAct.CD_Receipt_Issued__c ='Yes';
         testAct.CD_Property__c =  prop.Id;
            testAct.RecordTypeId = recotdtypeIdVal;
        list<CD_Activity__c> actList = new list<CD_Activity__c>();
        actList.add(testAct);
        insert actList;
        
         id recotdtypeIdVal2=Schema.SObjectType.CD_Activity__c.getRecordTypeInfosByDeveloperName().get('CD_Document').getRecordTypeId();
         CD_Activity__c testAct2 = new CD_Activity__c();
        testAct2.Name = 'Test activity';
       // testAct.CD_Payment__c ='test payment';
       // testAct.CD_Receipt_Issued__c ='Yes';
         testAct2.CD_Property__c =  prop.Id;
            testAct2.RecordTypeId = recotdtypeIdVal2;
        list<CD_Activity__c> actList2 = new list<CD_Activity__c>();
        actList2.add(testAct2);
         insert actList2;
         activityCreationCntrlr.getActivities(prop.id);
    }
    @isTest
    public static void test_getDocActivities()
    {
        User user1 = [SELECT Id,Email FROM User WHERE UserName = 'Texeira@sfdc.dev'];
        
        date expdate = system.today() +1;
        
         CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project1';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name = 'Test property1';
        prop.CD_Project__c = proj.id;
        prop.CD_isblocked__c = true;
        prop.CD_Unit_Number__c = 'Test Unit Number';
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        id recotdtypeIdVal=Schema.SObjectType.CD_Activity__c.getRecordTypeInfosByDeveloperName().get('CD_Document').getRecordTypeId();
        CD_Approval_Request__c aprReq = new CD_Approval_Request__c();
        aprReq.CD_Expiry_Date__c = expdate;
        aprReq.CD_Blocking_Comments__c = 'test comment1';
        aprReq.CD_Status__c = 'Pending';
        aprReq.Property__c = prop.Id;
        aprReq.CD_Approver_Name__c = user1.Id;
        aprReq.CD_Agent_Name__c = user1.Id;
        
        insert aprReq;
        
        CD_Activity__c testAct = new CD_Activity__c();
        testAct.Name = 'Test activity';
        testAct.CD_Payment__c ='test payment';
        testAct.CD_Receipt_Issued__c ='Yes';
         testAct.CD_Property__c =  prop.Id;
            testAct.RecordTypeId = recotdtypeIdVal;
        list<CD_Activity__c> actList = new list<CD_Activity__c>();
        actList.add(testAct);
        insert actList;
        
         id recotdtypeIdVal2=Schema.SObjectType.CD_Activity__c.getRecordTypeInfosByDeveloperName().get('CD_Document').getRecordTypeId();
         CD_Activity__c testAct2 = new CD_Activity__c();
        testAct2.Name = 'Test activity';
       // testAct.CD_Payment__c ='test payment';
       // testAct.CD_Receipt_Issued__c ='Yes';
         testAct2.CD_Property__c =  prop.Id;
            testAct2.RecordTypeId = recotdtypeIdVal2;
        list<CD_Activity__c> actList2 = new list<CD_Activity__c>();
        actList2.add(testAct2);
         insert actList2;
        string base64 ='testbase64value';
        string filname = 'Test file.pdf';
          activityCreationCntrlr.uploadFile(base64,filname,testAct2.id);
        activityCreationCntrlr.getFilesPreview(testAct2.id);
         activityCreationCntrlr.getDocActivities(prop.id);
    }
    
}