force-app/main/default/objects/CD_Project__c/CD_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/CD_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/fields/CD_Area__c.field-meta.xml
<CustomField>
    <fullName>CD_Area__c</fullName>
    <label>Area</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_isblocked__c.field-meta.xml
<CustomField>
    <fullName>CD_isblocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isblocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <label>Project</label>
    <referenceTo>CD_Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Red Listed Review</fullName>
            </value>
            <value>
                <fullName>Red Listed</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Property__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>false</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/CD_Property__c/recordTypes/Property.recordType-meta.xml
<RecordType>
    <fullName>Property</fullName>
    <active>true</active>
    <label>Property</label>
</RecordType>

force-app/main/default/objects/User/fields/gsir_company__c.field-meta.xml
<CustomField>
    <fullName>gsir_company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gulf Sotheby&apos;s</fullName>
            </value>
            <value>
                <fullName>Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Clark &amp; Scott</fullName>
                <isActive>false</isActive>
                <label>Clark &amp; Scott</label>
            </value>
            <value>
                <fullName>External Brokers</fullName>
                <isActive>false</isActive>
                <label>External Brokers</label>
            </value>
            <value>
                <fullName>Internal Brokers</fullName>
                <isActive>false</isActive>
                <label>Internal Brokers</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InquiryApprovalProcessRejectTest.cls
@IsTest
public class InquiryApprovalProcessRejectTest{
    @isTest
    public static void test_processApproval(){
        Test.startTest();
        
        User user1 = [SELECT Id FROM User WHERE Alias='ASale'];
        system.debug('user1 '+user1);
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        
        User umgr = new User(Alias = 'mstandt',gsir_company__c='UK',Email='manafer@testorg.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='manafer@testorg.com');
        insert umgr ;
        
        User u = new User(Alias = 'standt',gsir_company__c='UK', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com', managerid=umgr.id );
        
        
        // Create a test pba__Request__c record
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        System.debug('line 9' + proj);
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name ='Test property';
        prop.Status__c ='Available';
        prop.CD_Area__c ='Test';
        prop.CD_Project__c=proj.id;
        prop.CD_isblocked__c= true;
        prop.RecordTypeId = Schema.SObjectType.cd_Property__c.getRecordTypeInfosByName().get('Property').getRecordTypeId();
        insert prop;
        System.debug('line 19' + prop);
        
        pba__Request__c I = new  pba__Request__c();
        I.RecordTypeId = Schema.SObjectType.pba__Request__c.getRecordTypeInfosByName().get('Exclusive Project').getRecordTypeId();
        I.Unit__c = prop.Id;
        I.Pending_Request_to_Available_ExpiredDate__c = date.today();
        I.Approver__c=umgr.id;
        
        insert I;
        System.debug('pba request' + I.Id);
        System.debug('line 28' + I.RecordTypeId);     
        
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setComments('Rejecting Request.');
        req.setObjectId(I.Id);
     
        //Step 3:  Submit on behalf of a specific submitter
        req.setSubmitterId(u.id); 
        
        //Step 4:  Submit the record to specific process and skip the criteria evaluation
        req.setProcessDefinitionNameOrId('Red_List_Inquiry_Approval_Process');
        req.setSkipEntryCriteria(true);
        
        //req.getNextApproverIds()
        System.debug('line 39' + req);
        
        //Step 5:  Submit the approval request for the bid
        Approval.ProcessResult result = Approval.process(req);
        System.debug('line 42' + result);
        
        ProcessInstance processInstance = [SELECT Id, Status, TargetObjectId FROM ProcessInstance WHERE TargetObjectId = :I.Id];
        System.debug('processInstance in test class =' + processInstance.Status);
        
        ProcessInstanceWorkitem piwi= [SELECT Id,ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstanceId = :processInstance.Id];
        System.debug('ProcessInstanceWorkitem in test class =' + piwi.Id);
        //Id approvalRequestId = result.getInstanceId();
        
        list<string> recId = new list<string>();
        List<String> recIdList = new List<String>{I.Id};
            system.debug('recIdList '+recIdList);
        InquiryApprovalProcessReject.processApproval(recIdList);
        System.debug('line 45' + recIdList);
        Test.stopTest();
        
    }
}