force-app/main/default/objects/CD_Project__c/CD_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Project__c/fields/Imageurl__c.field-meta.xml
<CustomField>
    <fullName>Imageurl__c</fullName>
    <label>Imageurl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/CD_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/fields/CD_No_of_Beds__c.field-meta.xml
<CustomField>
    <fullName>CD_No_of_Beds__c</fullName>
    <label>No of Beds</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1BR</fullName>
            </value>
            <value>
                <fullName>2BR</fullName>
            </value>
            <value>
                <fullName>3BR</fullName>
            </value>
            <value>
                <fullName>4BR</fullName>
            </value>
            <value>
                <fullName>5BR</fullName>
            </value>
            <value>
                <fullName>6BR</fullName>
            </value>
            <value>
                <fullName>Garden Unit Duplex</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <label>Project</label>
    <referenceTo>CD_Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>CD_Unit_Number__c</fullName>
    <label>Unit Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_View__c.field-meta.xml
<CustomField>
    <fullName>CD_View__c</fullName>
    <label>View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1-bed Type A</fullName>
            </value>
            <value>
                <fullName>1-bed Type B</fullName>
            </value>
            <value>
                <fullName>2-bed Duplex Type 2A</fullName>
            </value>
            <value>
                <fullName>2-bed Duplex Type 2B</fullName>
            </value>
            <value>
                <fullName>2-bed Duplex Type 2C</fullName>
            </value>
            <value>
                <fullName>2-bed Duplex Type 2D</fullName>
            </value>
            <value>
                <fullName>2-bed Type A</fullName>
            </value>
            <value>
                <fullName>2-bed Type B</fullName>
            </value>
            <value>
                <fullName>2-bed Type C</fullName>
            </value>
            <value>
                <fullName>2-bed Type D</fullName>
            </value>
            <value>
                <fullName>2-bed Type E</fullName>
            </value>
            <value>
                <fullName>2-bed Type F</fullName>
            </value>
            <value>
                <fullName>2-bed Type H</fullName>
            </value>
            <value>
                <fullName>2-bed Type J</fullName>
            </value>
            <value>
                <fullName>3-bed Duplex Type 3A</fullName>
            </value>
            <value>
                <fullName>3-bed Type A</fullName>
            </value>
            <value>
                <fullName>3-bed Type B</fullName>
            </value>
            <value>
                <fullName>3-bed Type C</fullName>
            </value>
            <value>
                <fullName>3-bed Type D</fullName>
            </value>
            <value>
                <fullName>3-bed Type E</fullName>
            </value>
            <value>
                <fullName>4-bed Duplex Type 4A</fullName>
            </value>
            <value>
                <fullName>4-bed Duplex Type 4B</fullName>
            </value>
            <value>
                <fullName>ADGM SQUARE</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf / DIFC Burj Khalifa</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf / The Dubai Frame</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf / The Dubai Frame / Zaabeel</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf &amp; Burj Khalifa</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf &amp; The Dubai Frame</fullName>
            </value>
            <value>
                <fullName>Beach</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <formula>IF(
(ISPICKVAL(Status__c, &apos;Sold&apos;) &amp;&amp; ( $User.ProfileId  == &apos;00e1t000000HkGa&apos; || $User.ProfileId  == &apos;00e3X000001RysS&apos;)) || 
((CD_Project__c   == &apos;a2D7T000000tjS4&apos;  || CD_Project__c   == &apos;a2D7T000000tjpa&apos;) &amp;&amp; ( $User.ProfileId  == &apos;00e1t000000HkGa&apos; || $User.ProfileId  == &apos;00e3X000001RysS&apos;))
,Null
,CD_Sales_Price__c
)</formula>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Red Listed Review</fullName>
            </value>
            <value>
                <fullName>Red Listed</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectUnitsController.cls
public class ProjectUnitsController {
    @AuraEnabled(cacheable=true)
    
    public static List<CD_Project__c> getProjects() {
        return [SELECT Id, Name,Imageurl__c, (SELECT Id, Name, CD_Unit_Number__c,CD_No_of_Beds__c,Sales_Price__c,CD_View__c,Status__c FROM Properties__r) FROM CD_Project__c WHERE Name IN (
                    'Ritz Carlton Residences Business Bay', 
                    'The Private Residences DIFC', 
                    'Zabeel Saray Villas', 
                    'Ritz Carlton Ras Al Khaimah', 
                    'Eden house Canal', 
                    'Golden Tower',
                    'Corinthia Diriyah', 
                    'The Lancelot Collection', 
                    'Cityscape', 
                    'Four Seasons Abu Dhabi at Al Maryah Island', 
                    'The Ritz Carlton Diriyah', 
                    'Knightsbridge Gate', 
                    'Raffles Jeddah', 
                    'Baccarat Diriyah', 
                    'Canal Front', 
                    'Eden Hills', 
                    'Nobu Residences', 
                    'Rouge by Baccarat', 
                    'Dubai Harbour', 
                    'One & Only Penthouses', 
                    'DMCC uptown', 
                    'Seaside Hills', 
                    'Nobu Residences Tower B', 
                    'Nobu Residences Villas', 
                    'Nobu Residences Tower A', 
                    'Baccarat Residences', 
                    'Wasl', 
                    'One & Only', 
                    'One Zaabeel', 
                    'Beach Hills Villas')];
    }
   
    
}