force-app/main/default/objects/CD_Project__c/CD_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/CD_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/fields/CD_Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>CD_Bedrooms__c</fullName>
    <label>Bedrooms</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <label>Project</label>
    <referenceTo>CD_Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>CD_Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>CD_Unit_Number__c</fullName>
    <label>Unit Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Unit_Price_USD__c.field-meta.xml
<CustomField>
    <fullName>CD_Unit_Price_USD__c</fullName>
    <businessOwnerUser>sp@sothebysrealty.ae</businessOwnerUser>
    <complianceGroup>GDPR</complianceGroup>
    <label>Unit Price USD</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Red Listed Review</fullName>
            </value>
            <value>
                <fullName>Red Listed</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FetchProperty.cls
@RestResource(urlMapping='/getUnitDataFeed')
global with sharing class FetchProperty {
    @HttpGet
    global static list<CD_Property__c> fetchproperty(){
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        List<CD_Property__c> prop =[Select Id , Name , Status__c , CD_Unit_Number__c , CD_Project__r.Name , CD_Sales_Price__c ,CD_Unit_Price_USD__c, CD_Bedrooms__c from CD_Property__c WHERE CD_Project__r.Name ='DMCC uptown'  ];
        return prop ;
    }
}