force-app/main/default/objects/CD_Project__c/CD_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/CD_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/fields/CD_Area__c.field-meta.xml
<CustomField>
    <fullName>CD_Area__c</fullName>
    <label>Area</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <label>Project</label>
    <referenceTo>CD_Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Red Listed Review</fullName>
            </value>
            <value>
                <fullName>Red Listed</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P- {0000000}</displayFormat>
        <label>Payment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DLD fee</fullName>
            </value>
            <value>
                <fullName>VAT</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Conveyance Fee</fullName>
            </value>
            <value>
                <fullName>POA Fee</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>1st installment</fullName>
                <isActive>false</isActive>
                <label>1st installment</label>
            </value>
            <value>
                <fullName>2nd installment</fullName>
                <isActive>false</isActive>
                <label>2nd installment</label>
            </value>
            <value>
                <fullName>Admin Fees</fullName>
                <isActive>false</isActive>
                <label>Admin Fees</label>
            </value>
            <value>
                <fullName>Installment</fullName>
                <isActive>false</isActive>
                <label>Installment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Not Received</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Received By Developer</fullName>
            </value>
            <value>
                <fullName>Sent to Developer</fullName>
            </value>
            <value>
                <fullName>Cheque Bounced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>CD_Property__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestPaymentExtension.cls
@isTest(SeeAllData=true)
private class TestPaymentExtension {
   public static testmethod void  TestPaymentExtension() {
        try{  
           CD_Project__c proj = new CD_Project__c();
            proj.Account_Name__c ='test';
            insert proj;
            system.debug('proj'+proj);
            
           CD_Property__c unit = new CD_Property__c();
            unit.Name = 'test';
            unit.CD_Area__c = 'test';
            unit.CD_Project__c = proj.Id;
            insert unit;
            system.debug('unit'+unit);
            
            Payment__c Pay =new Payment__c();
            pay.Amount__c = 100;
          //pay.Payment_Date__c = 02/22/2023;
            pay.Payment_Type__c = 'Others';
            pay.Status__c = 'Received';
            pay.Unit__c = unit.Id;
            insert Pay;
            system.debug('Pay'+Pay);
            
             Apexpages.StandardController sc  = new Apexpages.StandardController(Pay);
             PaymentExtension ext = new PaymentExtension(sc);
             // System.assertEquals('firstlast@acme.com', leads[0].email);
            
           }catch(ListException e){
            System.debug('List exception fired');         
        }
}
}