force-app/main/default/objects/CD_Project__c/CD_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/CD_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <label>Project</label>
    <referenceTo>CD_Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Red Listed Review</fullName>
            </value>
            <value>
                <fullName>Red Listed</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Property__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>false</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/CD_Property__c/recordTypes/Property.recordType-meta.xml
<RecordType>
    <fullName>Property</fullName>
    <active>true</active>
    <label>Property</label>
</RecordType>

force-app/main/default/objects/RA_Request_Form__c/RA_Request_Form__c.object-meta.xml
<CustomObject>
    <label>RA Request Form</label>
    <nameField>
        <displayFormat>RA-{000}</displayFormat>
        <label>RA Request Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RA Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/projectStatusController_Test.cls
@isTest
public class projectStatusController_Test {
@isTest 
    Static void dogettest(){
        CD_Project__c testProject = new CD_Project__c(Name = 'Test Project');
        insert testProject;
        
        CD_Property__c testunit = new CD_Property__c();
        testunit.Name='test unit';
        testunit.CD_Project__c=testProject.id;
        insert testunit;
        ProjectStatusController controller = new ProjectStatusController(null);
        controller.selectedProjectId = testunit.Id;
        controller.selectedUnitId = 'someUnitId';
        Test.startTest();
        PageReference pageRef = controller.createRecord();
        Test.stopTest();
        
        System.assertNotEquals(null, pageRef);
        String expectedUrl = '/lightning/o/RA_Request_Form__c/new?recordTypeId=null&nooverride=1&def_lkid=someUnitId';
        //System.assertEquals(expectedUrl, pageRef.getUrl());
    }
    @isTest
    static void testFetchAvailableUnits() {
        // Create test data
        CD_Project__c testProject = new CD_Project__c(Name = 'Test Project');
        insert testProject;

        CD_Property__c testProperty = new CD_Property__c(Name = 'Test Property', CD_Project__c = testProject.Id, Status__c = 'Available');
        insert testProperty;

        ProjectStatusController controller = new ProjectStatusController(null);
        controller.selectedProjectId = testProject.Id;

        // Call the fetchAvailableUnits method
        Test.startTest();
        controller.fetchAvailableUnits();
        Test.stopTest();

        // Assert that availableUnits is not null and contains expected data
        System.assertNotEquals(null, controller.availableUnits);
        System.assertEquals(1, controller.availableUnits.size());
        System.assertEquals('Test Property', controller.availableUnits[0].unit.Name);
    }
}