force-app/main/default/objects/CD_Project__c/CD_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/CD_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <label>Project</label>
    <referenceTo>CD_Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Red Listed Review</fullName>
            </value>
            <value>
                <fullName>Red Listed</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Property__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>false</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/CD_Property__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>false</active>
    <label>RecordType</label>
</RecordType>

force-app/main/default/objects/RA_Request_Form__c/RA_Request_Form__c.object-meta.xml
<CustomObject>
    <label>RA Request Form</label>
    <nameField>
        <displayFormat>RA-{000}</displayFormat>
        <label>RA Request Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RA Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectStatusController.cls
public with sharing class ProjectStatusController {
    public List<UnitWrapper> availableUnits { get; set; }
    public Boolean showAvailableUnits { get; set; }
    public String selectedProjectId { get; set; }
    public List<SelectOption> projects { get; set; }
    public String selectedUnitId { get; set; }
    public String projectName { get; set; }
    
    public class UnitWrapper {
        public CD_Property__c unit { get; set; }
        public Boolean isSelected { get; set; }
        
        public UnitWrapper(CD_Property__c u) {
            unit = u;
            isSelected = false;
        }
    }
    
    public void fetchAvailableUnits() {
        if(String.isNotBlank(selectedProjectId)) {
            // Query to retrieve available units with status for the selected project
            List<CD_Property__c> units = [SELECT Id, Name, Status__c FROM CD_Property__c WHERE CD_Project__c = :selectedProjectId AND Status__c = 'Available' WITH SECURITY_ENFORCED];
            availableUnits = new List<UnitWrapper>();
            for (CD_Property__c unit : units) {
                availableUnits.add(new UnitWrapper(unit));
            }
            showAvailableUnits = true;
            projectName = [SELECT Name FROM CD_Project__c WHERE Id = :selectedProjectId].Name;
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a project.'));
            showAvailableUnits = false;
        }
    }
     
    
    public ProjectStatusController(ApexPages.StandardController controller) {
        projects = new List<SelectOption>();
        for(CD_Project__c proj : [SELECT Id, Name FROM CD_Project__c WITH SECURITY_ENFORCED]) {
            projects.add(new SelectOption(proj.Id, proj.Name));
        }
    }
    public PageReference createRecord() {
        String recordTypeId = ApexPages.currentPage().getParameters().get('RecordType'); // Retrieve the selected record type from the URL parameter
        String newRecordUrl = '/lightning/o/RA_Request_Form__c/new?recordTypeId=' + recordTypeId + '&nooverride=1';
        if (selectedUnitId != null) {
            newRecordUrl += '&def_lkid=' + selectedUnitId;        
        }
        return new PageReference(newRecordUrl);
    }
    
}