force-app/main/default/objects/Data__c/Data__c.object-meta.xml
<CustomObject>
    <label>Data Privacy</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Privacyes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Data__c/fields/App_URL__c.field-meta.xml
<CustomField>
    <fullName>App_URL__c</fullName>
    <label>App URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Data__c/fields/Credtional_Option__c.field-meta.xml
<CustomField>
    <fullName>Credtional_Option__c</fullName>
    <label>Credtional Option</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>KSA</fullName>
            </value>
            <value>
                <fullName>UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserDataController.cls
public class UserDataController {
 @AuraEnabled(cacheable=true)
    public static List<Data__c> getdata(String searchTerm) {
        String searchQuery = '%' + String.escapeSingleQuotes(searchTerm) + '%';
        return [SELECT Id, Name, Password__c,App_URL__c,Credtional_Option__c FROM Data__c WHERE Name LIKE :searchQuery];
    }
    @AuraEnabled(cacheable=true)
    public static List<ComboOption> getPicklistValues(String objectApiName, String fieldApiName) {
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Schema.SObjectType sobjType = gd.get(objectApiName);
        Schema.DescribeSObjectResult describeSObjectResult = sobjType.getDescribe();
        Schema.DescribeFieldResult fieldResult = describeSObjectResult.fields.getMap().get(fieldApiName).getDescribe();

        List<ComboOption> options = new List<ComboOption>();
        for (Schema.PicklistEntry pe : fieldResult.getPicklistValues()) {
            options.add(new ComboOption(pe.getLabel(), pe.getValue()));
        }
        return options;
    }

    public class ComboOption {
        @AuraEnabled public String label {get; set;}
        @AuraEnabled public String value {get; set;}

        public ComboOption(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
}