force-app/main/default/objects/Inquiry_Reassignment__c/Inquiry_Reassignment__c.object-meta.xml
<CustomObject>
    <description>This object captures each occasion when an Inquiry is reassigned from an agent based on a lack of activity such as 

- No status change or logged activity within the 24 hours after the Inquiry being assigned while in the &apos;Not Yet Contacted&apos; status
- No status change or logged activity within 7 days while in the &apos;Not Yet Contacted&apos;, &apos;Searching&apos;, &apos;Viewing&apos; status
- No status change or logged activity within 30 days while in the &apos;Offering&apos; status</description>
    <label>Inquiry Reassignment</label>
    <nameField>
        <displayFormat>Re-Assign-{000}</displayFormat>
        <label>Inquiry Reassignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiry Reassignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the agent that has had the Inquiry taken away (reassigned from..)</inlineHelpText>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inquiry_Reassignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/Inquiry_Status_when_Reassigned__c.field-meta.xml
<CustomField>
    <fullName>Inquiry_Status_when_Reassigned__c</fullName>
    <inlineHelpText>This is the &apos;Status&apos; of the Inquiry when it was reassigned</inlineHelpText>
    <label>Inquiry Status when Reassigned</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/IsQueue__c.field-meta.xml
<CustomField>
    <fullName>IsQueue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsQueue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/Reassigned_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Reassigned_Date_Time__c</fullName>
    <inlineHelpText>This is when this Inquiry record was reassigned</inlineHelpText>
    <label>Reassigned Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/Reassigned_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reassigned_Reason__c</fullName>
    <inlineHelpText>This is the reason (the associated workflow) that the Inquiry has been reassigned</inlineHelpText>
    <label>Reassigned Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Inquiry that has been reassigned from the agent</inlineHelpText>
    <label>Inquiry Record</label>
    <referenceTo>pba__Request__c</referenceTo>
    <relationshipLabel>Inquiry Reassignments</relationshipLabel>
    <relationshipName>Inquiry_Reassignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InquiriesReAssignmentJob.cls
global class InquiriesReAssignmentJob implements Database.Batchable<sObject>, Database.Stateful{
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String soql = 'SELECT ID,pba_uaefields__Community_Propertyfinder__c,OwnerId,pba__Status__c FROM pba__Request__c WHERE Assign_Owner_using_Assignment_Rules__c = true and LastModifiedDate <'+(System.now().addHours(-23).addMinutes(-59).format('yyyy-MM-dd\'T\'hh:mm:ss\'z\''));
        if(Test.isRunningTest()){
            soql = 'SELECT ID,pba_uaefields__Community_Propertyfinder__c,OwnerId,pba__Status__c FROM pba__Request__c WHERE B2B_Buyers_Full_Name__c = \'__TEST1__\' limit 1';        
        }
        return Database.getQueryLocator(soql);
    }
    
    public void execute(Database.BatchableContext BC, list<pba__Request__c> records){
        pba__Request__c currRecord;
        System.debug(records);
        for(sObject sObj: records){
            currRecord = (pba__Request__c) sObj;
            List<Inquiry_Reassignment__c> currReassignments = [select id,Agent__c from Inquiry_Reassignment__c where Request__c = :currRecord.Id];
            List<GroupMember> queueMembers = [select userOrGroupId from GroupMember where Group.Name = :'Inquiry Assignment: '+currRecord.pba_uaefields__Community_Propertyfinder__c];

            Set<Id> prevAgentIds = new Set<Id>();

            for(Inquiry_Reassignment__c ir : currReassignments){
                prevAgentIds.add(ir.Agent__c);
            }

            Boolean newAgentFlag = false;
            for(GroupMember gm : queueMembers){
                System.debug('Assigning to Queue Member');
                if(!prevAgentIds.contains(gm.userOrGroupId)){
                    currRecord.OwnerId = gm.userOrGroupId;
                    update currRecord;
                    insert new Inquiry_Reassignment__c(Request__c = currRecord.Id, Agent__c = gm.userOrGroupId, Reassigned_Date_Time__c = System.Now(), Reassigned_Reason__c = 'No Activity', Inquiry_Status_when_Reassigned__c = currRecord.pba__Status__c);
                    newAgentFlag = true;
                    break;
                }
            }

            if(!newAgentFlag){
                System.debug('Assigning back to Queue');
                Group g = [SELECT Id FROM Group where Name = :'Call Center'][0];
                currRecord.OwnerId = g.Id;
                update currRecord;
                insert new Inquiry_Reassignment__c(Request__c = currRecord.Id, IsQueue__c = true, Reassigned_Date_Time__c = System.Now(), Reassigned_Reason__c = 'No Activity', Inquiry_Status_when_Reassigned__c = currRecord.pba__Status__c);
            }


        }
    }
    
    public void finish(Database.BatchableContext BC){
        
    }
}