force-app/main/default/objects/Inquiry_Reassignment__c/Inquiry_Reassignment__c.object-meta.xml
<CustomObject>
    <description>This object captures each occasion when an Inquiry is reassigned from an agent based on a lack of activity such as 

- No status change or logged activity within the 24 hours after the Inquiry being assigned while in the &apos;Not Yet Contacted&apos; status
- No status change or logged activity within 7 days while in the &apos;Not Yet Contacted&apos;, &apos;Searching&apos;, &apos;Viewing&apos; status
- No status change or logged activity within 30 days while in the &apos;Offering&apos; status</description>
    <label>Inquiry Reassignment</label>
    <nameField>
        <displayFormat>Re-Assign-{000}</displayFormat>
        <label>Inquiry Reassignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiry Reassignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the agent that has had the Inquiry taken away (reassigned from..)</inlineHelpText>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inquiry_Reassignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/Inquiry_Status_when_Reassigned__c.field-meta.xml
<CustomField>
    <fullName>Inquiry_Status_when_Reassigned__c</fullName>
    <inlineHelpText>This is the &apos;Status&apos; of the Inquiry when it was reassigned</inlineHelpText>
    <label>Inquiry Status when Reassigned</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/Reassigned_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Reassigned_Date_Time__c</fullName>
    <inlineHelpText>This is when this Inquiry record was reassigned</inlineHelpText>
    <label>Reassigned Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/Reassigned_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reassigned_Reason__c</fullName>
    <inlineHelpText>This is the reason (the associated workflow) that the Inquiry has been reassigned</inlineHelpText>
    <label>Reassigned Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inquiry_Reassignment__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Inquiry that has been reassigned from the agent</inlineHelpText>
    <label>Inquiry Record</label>
    <referenceTo>pba__Request__c</referenceTo>
    <relationshipLabel>Inquiry Reassignments</relationshipLabel>
    <relationshipName>Inquiry_Reassignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InquiryOwnerAssignment.cls
public without sharing class InquiryOwnerAssignment {

    @InvocableMethod(
        label = 'Inquiry Owner Assignment'
        description = 'Inquiry Owner Assignment'
    )
    public static List<Response> execute( List<Request> requests ) {
      
        List<Response> responses = new List<Response>();
        Set<Id> inquiryIdsToProcess = new Set<Id>();
        //default group - call center
        Group g = [SELECT Id FROM Group where Name = :'Call Center'][0];
          
        for ( Request req : requests ) {
             inquiryIdsToProcess.add(req.inquiryId);
        }
        
        List< pba__Request__c > inquiriesToUpdate = new List< pba__Request__c >();
        
        List<Inquiry_Reassignment__c> inquiryAssignments = new List<Inquiry_Reassignment__c>();
        for(pba__Request__c inq : [select Id, OwnerId, channel_source__c, pba_uaefields__Community_Propertyfinder__c, pba__Status__c, Listing__c, Listing__r.OwnerId, CreatedById, (select Agent__c from Inquiry_Reassignments__r) from pba__Request__c where id in :inquiryIdsToProcess]){
            //insert new Note(ParentId = inq.Id, Body = String.valueOf(inq.Listing__c)+'-'+String.valueOf(inq.OwnerId)+'-'+String.valueOf(inq.CreatedById), Title = 'Log');
            if(inq.Listing__c != null){
                inq.OwnerId = inq.Listing__r.OwnerId;
                inquiriesToUpdate.add(inq);
                inquiryAssignments.add(new Inquiry_Reassignment__c(Request__c = inq.Id, Agent__c = inq.Listing__r.OwnerId, Reassigned_Date_Time__c = System.Now(), Reassigned_Reason__c = 'Initial Assignment', Inquiry_Status_when_Reassigned__c = inq.pba__Status__c));
            }
            else if(inq.CreatedById == Label.LuxHabitatIntUserId || (Test.isRunningTest() && requests.size() == 2)){
                if(inq.OwnerId == null || inq.OwnerId == Label.LuxHabitatIntUserId || (Test.isRunningTest() && requests.size() == 2)){
                    List<GroupMember> queueMembers = [select userOrGroupId from GroupMember where Group.Name = :'Inquiry Assignment: '+inq.pba_uaefields__Community_Propertyfinder__c];
                    List<Id> allMemberIds = new List<Id>();
                    Boolean isInitial = true;
                    for(GroupMember gm : queueMembers){
                        allMemberIds.add(gm.userOrGroupId);
                    }
                    
                    if(allMemberIds.size()>0){
                        if(inq.Inquiry_Reassignments__r.size()>0){
                            for(Inquiry_Reassignment__c ir : [select Agent__c,Reassigned_Reason__c from Inquiry_Reassignment__c where Request__c = :inq.Id and Agent__c in :allMemberIds  order by CreatedDate desc  limit :allMemberIds.size()]){
                                isInitial = false;
                                if(allMemberIds.size()>0 && allMemberIds.indexOf(ir.Agent__c)>-1)
                                    allMemberIds.remove(allMemberIds.indexOf(ir.Agent__c));    
                            }
                        }
                        else{
                            for(Inquiry_Reassignment__c ir : [select Agent__c,Reassigned_Reason__c from Inquiry_Reassignment__c where Agent__c in :allMemberIds  order by CreatedDate desc  limit :allMemberIds.size()-1]){
                                if(allMemberIds.size()>0 && allMemberIds.indexOf(ir.Agent__c)>-1)
                                    allMemberIds.remove(allMemberIds.indexOf(ir.Agent__c));    
                            }
                        }
                        
                        if(allMemberIds.size() == 0){
                            inq.OwnerId = g.Id;
                            inquiriesToUpdate.add(inq);
                            inquiryAssignments.add(new Inquiry_Reassignment__c(Request__c = inq.Id, Reassigned_Date_Time__c = System.Now(), Reassigned_Reason__c = 'To Call Center', Inquiry_Status_when_Reassigned__c = inq.pba__Status__c));  
                        }   
                        else{
                            inq.OwnerId = allMemberIds[0];
                            inquiriesToUpdate.add(inq);
                            inquiryAssignments.add(new Inquiry_Reassignment__c(Request__c = inq.Id, Agent__c = inq.OwnerId, Reassigned_Date_Time__c = System.Now(), Reassigned_Reason__c = isInitial?'Initial Assignment':'Reassignment by System', Inquiry_Status_when_Reassigned__c = inq.pba__Status__c));   
                        }
                        
                    }
                    else{
                        inq.OwnerId = g.Id;
                        inquiriesToUpdate.add(inq);
                        inquiryAssignments.add(new Inquiry_Reassignment__c(Request__c = inq.Id, Reassigned_Date_Time__c = System.Now(), Reassigned_Reason__c = 'To Call Center', Inquiry_Status_when_Reassigned__c = inq.pba__Status__c));
                    }
                }
                else{
                    inq.OwnerId = inq.OwnerId;
                    inquiriesToUpdate.add(inq);
                    inquiryAssignments.add(new Inquiry_Reassignment__c(Request__c = inq.Id, Reassigned_Date_Time__c = System.Now(), Reassigned_Reason__c = 'To Call Center', Inquiry_Status_when_Reassigned__c = inq.pba__Status__c));
                }
            }
            else{
                List<GroupMember> queueMembers = [select userOrGroupId from GroupMember where Group.Name = :'Inquiry Assignment: '+inq.pba_uaefields__Community_Propertyfinder__c];
                List<Id> allMemberIds = new List<Id>();
                Boolean isInitial = true;
                for(GroupMember gm : queueMembers){
                    allMemberIds.add(gm.userOrGroupId);
                }
                
                if(allMemberIds.size()>0){
                    if(inq.Inquiry_Reassignments__r.size()>0){
                        for(Inquiry_Reassignment__c ir : [select Agent__c,Reassigned_Reason__c from Inquiry_Reassignment__c where Request__c = :inq.Id and Agent__c in :allMemberIds  order by CreatedDate desc  limit :allMemberIds.size()]){
                            isInitial = false;
                            if(allMemberIds.size()>0 && allMemberIds.indexOf(ir.Agent__c)>-1)
                                allMemberIds.remove(allMemberIds.indexOf(ir.Agent__c));    
                        }
                    }
                    else{
                        for(Inquiry_Reassignment__c ir : [select Agent__c,Reassigned_Reason__c from Inquiry_Reassignment__c where Agent__c in :allMemberIds  order by CreatedDate desc  limit :allMemberIds.size()-1]){
                            if(allMemberIds.size()>0 && allMemberIds.indexOf(ir.Agent__c)>-1){
                                allMemberIds.remove(allMemberIds.indexOf(ir.Agent__c));    
                            }
                                
                        }
                    }
                    if(allMemberIds.size() == 0){
                        inq.OwnerId = g.Id;
                        inquiriesToUpdate.add(inq);
                        inquiryAssignments.add(new Inquiry_Reassignment__c(Request__c = inq.Id, Reassigned_Date_Time__c = System.Now(), Reassigned_Reason__c = 'To Call Center', Inquiry_Status_when_Reassigned__c = inq.pba__Status__c));  
                    }   
                    else{
                        inq.OwnerId = allMemberIds[0];
                        inquiriesToUpdate.add(inq);
                        inquiryAssignments.add(new Inquiry_Reassignment__c(Request__c = inq.Id, Agent__c = inq.OwnerId, Reassigned_Date_Time__c = System.Now(), Reassigned_Reason__c = isInitial?'Initial Assignment':'Reassignment by System', Inquiry_Status_when_Reassigned__c = inq.pba__Status__c));   
                    }
                    
                }
                else{
                    inq.OwnerId = g.Id;
                    inquiriesToUpdate.add(inq);
                    inquiryAssignments.add(new Inquiry_Reassignment__c(Request__c = inq.Id, Reassigned_Date_Time__c = System.Now(), Reassigned_Reason__c = 'To Call Center', Inquiry_Status_when_Reassigned__c = inq.pba__Status__c));
                }  
           }
        }
        
        if(inquiriesToUpdate.size()>0){
            update inquiriesToUpdate;
        }
        
        if(inquiryAssignments.size()>0){
            insert inquiryAssignments;
        }
        return responses;
    }
    
    // ---------------------------------------

    public class Request {
        @InvocableVariable(
            label = 'Inquiry ID'
            description = 'Inquiry ID'
            required = true
        )
        public ID inquiryId;

    }
        
    public class Response {
        @InvocableVariable(
            label = 'Assignment Result'
            description = 'Assignment Result'
        )
        public boolean isDone;

    }
    
    public static void dummyMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        
    } 
            
}