force-app/main/default/objects/OS_Property__c/OS_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Line__c/Payment_Line__c.object-meta.xml
<CustomObject>
    <label>Payment Plan Line Item</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plan Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Line__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Local Bank Transfer</fullName>
            </value>
            <value>
                <fullName>International Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Manger cheque</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Line__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Line__c/fields/Paid_date__c.field-meta.xml
<CustomField>
    <fullName>Paid_date__c</fullName>
    <label>Paid Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Line__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/PaymentController.cls
public class PaymentController {
 @AuraEnabled(cacheable=true)
    public static List<Payment_Line__c > getPaymentsByOrder() {
        return [SELECT Id ,Order__c , Paid_Amount__c, Paid_date__c, Payment_Date__c, Percentage__c , Name,Mode_of_Payment__c
FROM Payment_Line__c 
WHERE Order__c  IN ('1', '2', '3', '4', '5', '6', '7')
ORDER BY Order__c 
];
    }
    @AuraEnabled
    public static void updatePayments(List<Payment_Line__c > payments) {
        try {
            upsert payments;
        } catch(Exception e) {
            throw new AuraHandledException('Error updating payments: ' + e.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<Master_plan__c > getPlanOrder2() {
        return [SELECT Id, Order__c , Name FROM Master_plan__c WHERE Order__c  IN ('3', '7', '8', '9') 
ORDER BY Order__c
];
    }
    @AuraEnabled(cacheable=true)
    public static List<Master_plan__c > getplanOrder() {
        return [SELECT Id ,Order__c ,Name FROM Master_plan__c WHERE Order__c  IN ('1', '2', '3', '4', '5', '6', '7')
ORDER BY Order__c 
];
    }
    @AuraEnabled(cacheable=true)
    public static List<OS_Property__c> getUnitDetails() {
        return [SELECT Id, Name FROM OS_Property__c];
    }
   
    }