force-app/main/default/objects/Contact/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agency</fullName>
                <label>3rd Party Agency</label>
            </value>
            <value>
                <fullName>Agency Client</fullName>
                <label>3rd Party Agency Client</label>
            </value>
            <value>
                <fullName>Agent</fullName>
                <label>3rd Party Agent</label>
            </value>
            <value>
                <fullName>Agents</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Property Manager</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>Referred Contact</fullName>
            </value>
            <value>
                <fullName>Search Agent</fullName>
            </value>
            <value>
                <fullName>Seller</fullName>
            </value>
            <value>
                <fullName>Solicitor</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Mobile_country_codes__c.field-meta.xml
<CustomField>
    <fullName>Mobile_country_codes__c</fullName>
    <label>Mobile country codes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mobile_country_codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Other_Email__c.field-meta.xml
<CustomField>
    <fullName>Other_Email__c</fullName>
    <label>Alternative Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pba__CompanyName__c.field-meta.xml
<CustomField>
    <fullName>pba__CompanyName__c</fullName>
    <label>Company</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Phone_Country_Code__c</fullName>
    <label>Phone Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sharing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Rule__c</fullName>
    <defaultValue>&quot;Private&quot;</defaultValue>
    <label>Sharing Rule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open to All Countries</fullName>
                <color>#B6E32E</color>
                <label>Open to All Countries</label>
            </value>
            <value>
                <fullName>Private</fullName>
                <color>#993399</color>
                <label>Private</label>
            </value>
            <value>
                <fullName>Exclusive Project UAE</fullName>
                <color>#663366</color>
                <label>Exclusive Project UAE</label>
            </value>
            <value>
                <fullName>UK Sothebys International Realty</fullName>
                <color>#F96FB7</color>
                <label>UK Sotheby&apos;s International Realty</label>
            </value>
            <value>
                <fullName>Saudi Arabia Sothebys International Realty</fullName>
                <color>#FF9900</color>
                <label>Saudi Arabia Sotheby&apos;s International Realty</label>
            </value>
            <value>
                <fullName>UAE Sotheby&apos;s International Realty</fullName>
                <color>#33CCFF</color>
                <label>UAE Sotheby&apos;s International Realty</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>+1	Canada</fullName>
    </customValue>
    <customValue>
        <fullName>+1	United States</fullName>
    </customValue>
    <customValue>
        <fullName>+1242	Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>+1246	Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>+1264	Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>+1268	Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>+1284	Virgin Islands</fullName>
    </customValue>
    <customValue>
        <fullName>+1340	Virgin Islands, U.S.</fullName>
    </customValue>
    <customValue>
        <fullName>+1441	Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>+1473	Grenada</fullName>
    </customValue>
    <customValue>
        <fullName>+1649	Turks and Caicos Islands</fullName>
    </customValue>
    <customValue>
        <fullName>+1664	Montserrat</fullName>
    </customValue>
    <customValue>
        <fullName>+1670	Northern Mariana Islands</fullName>
    </customValue>
    <customValue>
        <fullName>+1671	Guam</fullName>
    </customValue>
    <customValue>
        <fullName>+1684	American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>+1758	Saint Lucia</fullName>
    </customValue>
    <customValue>
        <fullName>+1767	Dominica</fullName>
    </customValue>
    <customValue>
        <fullName>+1784	Saint Vincent and the Grenadines</fullName>
    </customValue>
    <customValue>
        <fullName>+1849	Dominican Republic</fullName>
    </customValue>
    <customValue>
        <fullName>+1868	Trinidad and Tobago</fullName>
    </customValue>
    <customValue>
        <fullName>+1869	Saint Kitts and Nevis</fullName>
    </customValue>
    <customValue>
        <fullName>+1876	Jamaica</fullName>
    </customValue>
    <customValue>
        <fullName>+1939	Puerto Rico</fullName>
    </customValue>
    <customValue>
        <fullName>+20	Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>+211	South Sudan</fullName>
    </customValue>
    <customValue>
        <fullName>+212	Morocco</fullName>
    </customValue>
    <customValue>
        <fullName>+213	Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>+216	Tunisia</fullName>
    </customValue>
    <customValue>
        <fullName>+218	Libyan Arab Jamahiriya</fullName>
    </customValue>
    <customValue>
        <fullName>+220	Gambia</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Mobile_country_codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>+93</fullName>
    </customValue>
    <customValue>
        <fullName>+355</fullName>
    </customValue>
    <customValue>
        <fullName>+213</fullName>
    </customValue>
    <customValue>
        <fullName>+1-684</fullName>
    </customValue>
    <customValue>
        <fullName>+376</fullName>
    </customValue>
    <customValue>
        <fullName>+244</fullName>
    </customValue>
    <customValue>
        <fullName>+1-264</fullName>
    </customValue>
    <customValue>
        <fullName>+672</fullName>
    </customValue>
    <customValue>
        <fullName>+1-268</fullName>
    </customValue>
    <customValue>
        <fullName>+54</fullName>
    </customValue>
    <customValue>
        <fullName>+374</fullName>
    </customValue>
    <customValue>
        <fullName>+297</fullName>
    </customValue>
    <customValue>
        <fullName>+61</fullName>
    </customValue>
    <customValue>
        <fullName>+43</fullName>
    </customValue>
    <customValue>
        <fullName>+994</fullName>
    </customValue>
    <customValue>
        <fullName>+1-242</fullName>
    </customValue>
    <customValue>
        <fullName>+973</fullName>
    </customValue>
    <customValue>
        <fullName>+880</fullName>
    </customValue>
    <customValue>
        <fullName>+1-246</fullName>
    </customValue>
    <customValue>
        <fullName>+375</fullName>
    </customValue>
    <customValue>
        <fullName>+32</fullName>
    </customValue>
    <customValue>
        <fullName>+501</fullName>
    </customValue>
    <customValue>
        <fullName>+229</fullName>
    </customValue>
    <customValue>
        <fullName>+1-441</fullName>
    </customValue>
    <customValue>
        <fullName>+975</fullName>
    </customValue>
    <customValue>
        <fullName>+591</fullName>
    </customValue>
    <customValue>
        <fullName>+387</fullName>
    </customValue>
    <customValue>
        <fullName>+267</fullName>
    </customValue>
    <customValue>
        <fullName>+55</fullName>
    </customValue>
    <customValue>
        <fullName>+246</fullName>
    </customValue>
    <masterLabel>Mobile country code2</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConSearchcontroller.cls
/**
* @description   This Apex class provides methods for searching existing contacts, 
*                creating new contacts, and fetching picklist values for a specified object field.
* @author        Sprutiraj
* Modification Log:
* Ver   Date         Author                Modification
* 1.0   12/1/2024   Sprutiraj             Initial Version
*/
public class ConSearchcontroller {
    public Contact newContact { get; set; }
    public List<Contact> duplicateContacts { get; set; }
    public Boolean showDuplicateContacts { get; set; }
    
    public ConSearchcontroller(ApexPages.StandardController stdController) {
        newContact = (Contact)stdController.getRecord();
        newContact = new Contact();
        duplicateContacts = new List<Contact>();
        showDuplicateContacts = false;
        
    }
    
    public PageReference saveContact() {
   
        if (String.isBlank(newContact.Email) && String.isBlank(newContact.Phone) && String.isBlank(newContact.MobilePhone)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please provide at least one of the following: Email, Phone, or Mobile Phone.'));
            return null;
        }
        // Check for duplicates by last name
        String lastName = newContact.LastName;
        String fuzzyLastName = '%' + lastName + '%';
        String phone =newContact.Phone;
        String email=newContact.Email;
        String mobilephone=newContact.MobilePhone;
        if (String.isBlank(phone)) {
            phone = null;
        }
        if (String.isBlank(email)) {
            email = null;
        }
        if (String.isBlank(mobilephone)) {
            mobilephone = null;
        }
        if(newContact != null){
            if (newContact.Id != null) {
                duplicateContacts = [SELECT Id, Salutation, RecordType.Name,Phone_Country_Code__c,Other_Email__c, Name,Mobile_Country_Codes__c, pba__CompanyName__c, Email, Phone, MobilePhone, ContactType__c	, Sharing_Rule__c	, LeadSource 
                                     FROM Contact 
                                     WHERE Id != :newContact.Id 
                                     AND (Phone = :phone OR Email = :email OR MobilePhone = :mobilephone OR Phone = :mobilephone OR mobilephone=:Phone)
                                    ];
            } else {
                duplicateContacts = [SELECT Id, Salutation, RecordType.Name, Name,Mobile_Country_Codes__c,Other_Email__c,Phone_Country_Code__c	, pba__CompanyName__c, Email, Phone, MobilePhone, ContactType__c	, Sharing_Rule__c	, LeadSource
                                     FROM Contact 
                                     WHERE Id != :newContact.Id 
                                     AND Phone = :phone 
                                     AND Email = :email 
                                     AND MobilePhone = :mobilephone
                                    ];
            }
            
            if (duplicateContacts.isEmpty()) {
                createOrUpdateAccount();
                insert newContact;
                //newContact = new Contact();
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Contact saved successfully'));
                //newContact = new Contact(); // Clear the form for the next entry
                PageReference contactDetailPage = new PageReference('/' + newContact.Id);
                contactDetailPage.setRedirect(true);
                return contactDetailPage;
                
            } else {
                showDuplicateContacts = true;
                // Duplicates found, show a message
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Duplicate contacts found.'));
                return null;
            }
        }
        return null;
    }
    public void createOrUpdateAccount() {
        if (String.isNotBlank(newContact.AccountId)) {
            System.debug('AccountId: ' + newContact.AccountId);
            
            // Check if an Account with the specified Company Name already exists
            try {
                Account existingAccount = [SELECT Id FROM Account WHERE Name = :newContact.AccountId LIMIT 1];
                System.debug('Existing Account: ' + existingAccount);
                
                if (existingAccount == null) {
                    // If the Account does not exist, create a new one
                    Account newAccount = new Account(
                        Name = newContact.AccountId
                        // Add other fields as needed
                    );
                    insert newAccount;
                    newContact.AccountId = newAccount.Id;
                    System.debug('New Account created: ' + newAccount.Id);
                } else {
                    // If the Account already exists, link the Contact to the existing Account
                    newContact.AccountId = existingAccount.Id;
                    System.debug('Linking to existing Account: ' + existingAccount.Id);
                }
            } catch (Exception e) {
                System.debug('Error creating/updating Account: ' + e.getMessage());
            }
        }
    }
    
    
    public PageReference cancel() {
        // Redirect to the Contact recent view
        return new PageReference('/lightning/o/Contact/list?filterName=Recent');
    }
}