force-app/main/default/objects/Contact/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agency</fullName>
                <label>3rd Party Agency</label>
            </value>
            <value>
                <fullName>Agency Client</fullName>
                <label>3rd Party Agency Client</label>
            </value>
            <value>
                <fullName>Agent</fullName>
                <label>3rd Party Agent</label>
            </value>
            <value>
                <fullName>Agents</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Property Manager</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>Referred Contact</fullName>
            </value>
            <value>
                <fullName>Search Agent</fullName>
            </value>
            <value>
                <fullName>Seller</fullName>
            </value>
            <value>
                <fullName>Solicitor</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sharing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Rule__c</fullName>
    <defaultValue>&quot;Private&quot;</defaultValue>
    <label>Sharing Rule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open to All Countries</fullName>
                <color>#B6E32E</color>
                <label>Open to All Countries</label>
            </value>
            <value>
                <fullName>Private</fullName>
                <color>#993399</color>
                <label>Private</label>
            </value>
            <value>
                <fullName>Exclusive Project UAE</fullName>
                <color>#663366</color>
                <label>Exclusive Project UAE</label>
            </value>
            <value>
                <fullName>UK Sothebys International Realty</fullName>
                <color>#F96FB7</color>
                <label>UK Sotheby&apos;s International Realty</label>
            </value>
            <value>
                <fullName>Saudi Arabia Sothebys International Realty</fullName>
                <color>#FF9900</color>
                <label>Saudi Arabia Sotheby&apos;s International Realty</label>
            </value>
            <value>
                <fullName>UAE Sotheby&apos;s International Realty</fullName>
                <color>#33CCFF</color>
                <label>UAE Sotheby&apos;s International Realty</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UKAddressPVControllerTest.cls
@isTest
public class UKAddressPVControllerTest {

    @isTest
    static void testConstructor() {
       Contact testContact = new Contact();
           testContact.FirstName = 'Johne';
            testContact.LastName = 'Doee';  
        testContact.ContactType__c='Client';
        testContact.Sharing_Rule__c='Private';
       
        
        insert testContact;

        Test.setCurrentPageReference(new PageReference('/apex/yourPageName?id=' + testContact.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(testContact);

        UKAddressController controller = new UKAddressController(sc);

        // Add your assertions here to check if the controller values are set correctly
        System.assertEquals(testContact.Id, controller.currentRecordId);
        // Add more assertions for other controller properties
    }
    
    @isTest
    static void testSavePropertyValuation() {
        // Create a test Contact
        Contact testContact = new Contact();
        testContact.FirstName = 'John';
        testContact.LastName = 'Doe';  
        testContact.ContactType__c='Client';
        testContact.Sharing_Rule__c='Private';
        
        
        insert testContact;

        // Create a test UKAddressPVController instance
        ApexPages.StandardController sc = new ApexPages.StandardController(testContact);
        UKAddressPVController controller = new UKAddressPVController(sc);

        // Set required fields for the newPropertyValuation
        controller.SubBuilding = 'SubBuilding';
        controller.BuildingName = 'BuildingName';
        controller.BuildingNumber = 'BuildingNumber';
        controller.StreetSubcommunity = 'StreetSubcommunity';
        controller.DistrictCommunity = 'DistrictCommunity';
        controller.CityCommunity = 'CityCommunity';
        controller.ProvienceState = 'ProvienceState';
        controller.PostalCode = '12345';
        controller.country = 'United Kingdom';
        controller.PropertyfinderRegion = 'SubBuilding BuildingName BuildingNumber,StreetSubcommunity,CityCommunity,DistrictCommunity,ProvienceState,12345,United Kingdom';
        controller.showField3=true;
        controller.errorMessage='Please Select Area/Town from dropdown values';
        controller.rectype='Rent';
        controller.picklistValues = new List<SelectOption>{
    new SelectOption('Rent', 'Rent'),
    new SelectOption('Sale', 'Sale')
};
        // Set controller properties
     /*   controller.BuildingName = 'Test Building';
        controller.StreetSubcommunity = 'Test Street';
        controller.PostalCode ='100 123';
        controller.showSpinner = true;*/
        // Set other properties as needed

        // Start the spinner
        controller.startSpinner();
        controller.showField3Button();
        // Save the Property Valuation
        Test.startTest();
        controller.savePropertyValuation();
        Test.stopTest();

        // Verify if the spinner has stopped
      //  System.assertEquals(false, controller.showSpinner);

        // Add additional assertions as needed based on your implementation
    }

    // Add more test methods as needed for other functionalities in the controller
}