force-app/main/default/objects/Contact/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agency</fullName>
                <label>3rd Party Agency</label>
            </value>
            <value>
                <fullName>Agency Client</fullName>
                <label>3rd Party Agency Client</label>
            </value>
            <value>
                <fullName>Agent</fullName>
                <label>3rd Party Agent</label>
            </value>
            <value>
                <fullName>Agents</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Property Manager</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>Referred Contact</fullName>
            </value>
            <value>
                <fullName>Search Agent</fullName>
            </value>
            <value>
                <fullName>Seller</fullName>
            </value>
            <value>
                <fullName>Solicitor</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Mobile_country_code__c.field-meta.xml
<CustomField>
    <fullName>Mobile_country_code__c</fullName>
    <label>Mobile Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mobile_country_codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/Trigger_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger setting</label>
</CustomObject>

force-app/main/default/objects/Trigger_Setting__c/fields/Is_Contact_Trigger_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Is_Contact_Trigger_Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Contact Trigger Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Mobile_country_codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>+93</fullName>
    </customValue>
    <customValue>
        <fullName>+355</fullName>
    </customValue>
    <customValue>
        <fullName>+213</fullName>
    </customValue>
    <customValue>
        <fullName>+1-684</fullName>
    </customValue>
    <customValue>
        <fullName>+376</fullName>
    </customValue>
    <customValue>
        <fullName>+244</fullName>
    </customValue>
    <customValue>
        <fullName>+1-264</fullName>
    </customValue>
    <customValue>
        <fullName>+672</fullName>
    </customValue>
    <customValue>
        <fullName>+1-268</fullName>
    </customValue>
    <customValue>
        <fullName>+54</fullName>
    </customValue>
    <customValue>
        <fullName>+374</fullName>
    </customValue>
    <customValue>
        <fullName>+297</fullName>
    </customValue>
    <customValue>
        <fullName>+61</fullName>
    </customValue>
    <customValue>
        <fullName>+43</fullName>
    </customValue>
    <customValue>
        <fullName>+994</fullName>
    </customValue>
    <customValue>
        <fullName>+1-242</fullName>
    </customValue>
    <customValue>
        <fullName>+973</fullName>
    </customValue>
    <customValue>
        <fullName>+880</fullName>
    </customValue>
    <customValue>
        <fullName>+1-246</fullName>
    </customValue>
    <customValue>
        <fullName>+375</fullName>
    </customValue>
    <customValue>
        <fullName>+32</fullName>
    </customValue>
    <customValue>
        <fullName>+501</fullName>
    </customValue>
    <customValue>
        <fullName>+229</fullName>
    </customValue>
    <customValue>
        <fullName>+1-441</fullName>
    </customValue>
    <customValue>
        <fullName>+975</fullName>
    </customValue>
    <customValue>
        <fullName>+591</fullName>
    </customValue>
    <customValue>
        <fullName>+387</fullName>
    </customValue>
    <customValue>
        <fullName>+267</fullName>
    </customValue>
    <customValue>
        <fullName>+55</fullName>
    </customValue>
    <customValue>
        <fullName>+246</fullName>
    </customValue>
    <customValue>
        <fullName>+221</fullName>
    </customValue>
    <masterLabel>Mobile country code2</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactTriggerHandlerTest.cls
@isTest
public class ContactTriggerHandlerTest {
    @isTest
    Public static void createcontact_when_trigger_is_active()
    {
        //Create Custom Setting 
        Trigger_Setting__c cs=new Trigger_Setting__c();
        cs.Is_Contact_Trigger_Inactive__c=false;
        cs.SetupOwnerId = UserInfo.getOrganizationId();
        insert cs;
        
        //Create new Contact Record
        Contact con=new Contact();
        con.firstName='Test';
        con.LastName='ABC';
        Con.Phone='12356';
        con.Mobile_country_code__c='+93';
        con.ContactType__c='Buyer';
        insert con;
        
        //Create new Contact and Update Mobile Country Code
        Contact t1=new Contact();
        t1.Id=con.Id;
        t1.Mobile_country_code__c='+221';
        update t1;
      
    }  
    
    @isTest
    Public static void createcontact_when_trigger_is_inactive()
    {
        //Create Custom Setting 
        Trigger_Setting__c cs=new Trigger_Setting__c();
        cs.Is_Contact_Trigger_Inactive__c=true;
        cs.SetupOwnerId = UserInfo.getOrganizationId();
        insert cs;
        
        //Create new Contact Record
        Contact con=new Contact();
        con.firstName='Test';
        con.LastName='ABC';
        Con.Phone='12356';
        con.Mobile_country_code__c='+93';
        con.ContactType__c='Buyer';
        insert con;
        
        //Create new Contact and Update Mobile Country Code
        Contact t1=new Contact();
        t1.Id=con.Id;
        t1.Mobile_country_code__c='+221';
        update t1;
      
    }    
}