force-app/main/default/objects/Contact/fields/Mobile_Country__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Country__c</fullName>
    <label>Mobile Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mobile_country_code__c.field-meta.xml
<CustomField>
    <fullName>Mobile_country_code__c</fullName>
    <label>Mobile Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mobile_country_codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country_Code__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Mobile_country_codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>+93</fullName>
    </customValue>
    <customValue>
        <fullName>+355</fullName>
    </customValue>
    <customValue>
        <fullName>+213</fullName>
    </customValue>
    <customValue>
        <fullName>+1-684</fullName>
    </customValue>
    <customValue>
        <fullName>+376</fullName>
    </customValue>
    <customValue>
        <fullName>+244</fullName>
    </customValue>
    <customValue>
        <fullName>+1-264</fullName>
    </customValue>
    <customValue>
        <fullName>+672</fullName>
    </customValue>
    <customValue>
        <fullName>+1-268</fullName>
    </customValue>
    <customValue>
        <fullName>+54</fullName>
    </customValue>
    <customValue>
        <fullName>+374</fullName>
    </customValue>
    <customValue>
        <fullName>+297</fullName>
    </customValue>
    <customValue>
        <fullName>+61</fullName>
    </customValue>
    <customValue>
        <fullName>+43</fullName>
    </customValue>
    <customValue>
        <fullName>+994</fullName>
    </customValue>
    <customValue>
        <fullName>+1-242</fullName>
    </customValue>
    <customValue>
        <fullName>+973</fullName>
    </customValue>
    <customValue>
        <fullName>+880</fullName>
    </customValue>
    <customValue>
        <fullName>+1-246</fullName>
    </customValue>
    <customValue>
        <fullName>+375</fullName>
    </customValue>
    <customValue>
        <fullName>+32</fullName>
    </customValue>
    <customValue>
        <fullName>+501</fullName>
    </customValue>
    <customValue>
        <fullName>+229</fullName>
    </customValue>
    <customValue>
        <fullName>+1-441</fullName>
    </customValue>
    <customValue>
        <fullName>+975</fullName>
    </customValue>
    <customValue>
        <fullName>+591</fullName>
    </customValue>
    <customValue>
        <fullName>+387</fullName>
    </customValue>
    <customValue>
        <fullName>+267</fullName>
    </customValue>
    <customValue>
        <fullName>+55</fullName>
    </customValue>
    <customValue>
        <fullName>+246</fullName>
    </customValue>
    <masterLabel>Mobile country code2</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactTriggerHandler.cls
public class ContactTriggerHandler {
    Public static void UpdateCountry(List<Contact> conList ,Map<Id,Contact> conUpdate)
    {
      	List<Country_Code__mdt> CountryCodeLst = New List<Country_Code__mdt>([SELECT Id, Label, DeveloperName,Country_Code__c FROM Country_Code__mdt]);
       Map<String,String> ApiToLabelMap = new Map<String,String>();         
        For(Country_Code__mdt sp : CountryCodeLst)
	   { 
		  ApiToLabelMap.put(sp.Country_Code__c,sp.Label);
           System.debug('Label value of picklist>>'+ ApiToLabelMap);
	   }      
        List<Contact> countryCodeList = new List<Contact>();
        for(Contact conrecord:conList)
        {
            if((conrecord.Mobile_country_code__c!= Null) && 
 			((conUpdate == Null) || (conUpdate!=null && conrecord.Mobile_country_code__c!=conUpdate.get(conrecord.Id).Mobile_country_code__c)))
            {
                //Check Metadata Country Code is equal as Contact Country code.
                if(ApiToLabelMap.containsKey(conrecord.Mobile_country_code__c))
                {
                    //Update metadata Country Code into contact Mobile Country Code.
                    conrecord.Mobile_Country__c=ApiToLabelMap.get(conrecord.Mobile_country_code__c);
                    countryCodeList.add(conrecord); 
                }
                
            }       
            system.debug('Create or Update Contact with Country name');  
        }
    }
}