force-app/main/default/objects/CD_Approval_Request__c/CD_Approval_Request__c.object-meta.xml
<CustomObject>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Approval_Comment__c.field-meta.xml
<CustomField>
    <fullName>CD_Approval_Comment__c</fullName>
    <label>Approval Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Approval_Rejection_Action__c.field-meta.xml
<CustomField>
    <fullName>CD_Approval_Rejection_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approval / Rejection Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Approval_Rejection_Date__c.field-meta.xml
<CustomField>
    <fullName>CD_Approval_Rejection_Date__c</fullName>
    <label>Approval/Rejection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Defer_Comments__c.field-meta.xml
<CustomField>
    <fullName>CD_Defer_Comments__c</fullName>
    <label>Defer Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>CD_Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Status__c.field-meta.xml
<CustomField>
    <fullName>CD_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>CD_Property__c</referenceTo>
    <relationshipLabel>Approval Requests</relationshipLabel>
    <relationshipName>Approval_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/batchApexOnApprovalReq.cls
public class batchApexOnApprovalReq implements database.Batchable<Sobject> {
	
      public database.QueryLocator start(database.BatchableContext bc){
        
    	date curDate = system.today();
        system.debug('get today date'+curDate);
         // string strQuery = 'select id,CD_Approval_Comment__c, CD_Expiry_Date__c,CD_Status__c, CD_Defer_Comments__c,  Property__c from CD_Approval_Request__c where CD_Expiry_Date__c =' +curDate;
        return database.getQueryLocator([select id,CD_Approval_Comment__c, CD_Expiry_Date__c,CD_Status__c, CD_Defer_Comments__c,  Property__c from CD_Approval_Request__c 
        where CD_Expiry_Date__c =: curDate]);
    
    }
     public void execute(database.BatchableContext bc, List<CD_Approval_Request__c> scope)
     {
         set<id> propIds = new set<id>();
         list<CD_Approval_Request__c>  aprReqIds = new list<CD_Approval_Request__c>();
         system.debug('inside execution outer');

         for(CD_Approval_Request__c aprReq : scope )
         {
             propIds.add(aprReq.Property__c);
             aprReqIds.add(aprReq);
         }
         // String message =''; 
         system.debug('inside for loop of execute outer');

         string processType = 'Reject';
        String comments = processType == 'Approve' ? 'Approved' : 'Rejected';
        string appCom = 'Expiry Date met';
        list <ProcessInstanceWorkitem> storeWorkItem = [Select Id FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId =: propIds];
         
         for(ProcessInstanceWorkitem piwi : storeWorkItem )
         {
             	Approval.ProcessWorkitemRequest objWorkItemRequest = new Approval.ProcessWorkitemRequest();
        
       	    objWorkItemRequest.setComments(appCom);
            objWorkItemRequest.setAction(processType);//approve or reject
            objWorkItemRequest.setWorkitemId(piwi.Id);
             
             Approval.ProcessResult processResult = Approval.Process(objWorkItemRequest,False);
         }
         
         for(CD_Approval_Request__c aprReq :aprReqIds)
         {
             aprReq.CD_Approval_Comment__c ='Declined due to request expiry';
             aprReq.CD_Status__c='Declined';
             aprReq.CD_Approval_Rejection_Action__c = true;
             aprReq.CD_Approval_Rejection_Date__c = system.today();
         }
         
         update aprReqIds;
         system.debug('execute outer');
     }
    public void finish(database.BatchableContext bc){
        system.debug('>>>>>>Finish');
    }
}