force-app/main/default/objects/CD_Approval_Request__c/CD_Approval_Request__c.object-meta.xml
<CustomObject>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Agent_Email__c.field-meta.xml
<CustomField>
    <fullName>CD_Agent_Email__c</fullName>
    <formula>CD_Agent_Name__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_AgentName_txt__c.field-meta.xml
<CustomField>
    <fullName>CD_AgentName_txt__c</fullName>
    <formula>CD_Agent_Name__r.FirstName</formula>
    <label>AgentName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Approver__c.field-meta.xml
<CustomField>
    <fullName>CD_Approver__c</fullName>
    <formula>CD_Approver_Name__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ApproverName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>CD_Approver_Email__c</fullName>
    <formula>CD_Approver_Name__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approver Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>CD_Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>CD_Property_Name__c</fullName>
    <formula>Property__r.CD_Unit_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Status__c.field-meta.xml
<CustomField>
    <fullName>CD_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>CD_Property__c</referenceTo>
    <relationshipLabel>Approval Requests</relationshipLabel>
    <relationshipName>Approval_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchEmail.cls
public class BatchEmail  implements database.Batchable<sObject>{
    
    public database.QueryLocator start(database.BatchableContext bc){
        date curDate = system.today()+1;
        //return (database.getQueryLocator([select id,lastName,email  from contact ]));
        system.debug('inside start');
        
        return ( database.getQueryLocator([select id, CD_Approver__c, CD_Approver_Email__c, CD_AgentName_txt__c, CD_Property_Name__c, Property__c from CD_Approval_Request__c where CD_Status__c='Pending'and CD_Expiry_Date__c =:curDate ]));        
    }
    public void execute(database.BatchableContext bc,list<CD_Approval_Request__c>lstAprl){
        system.debug('inside execute');
        System.debug('lstAprl is '+lstAprl);
        
        //User ur = [SELECT Id, Name FROM User WHERE Name = 'Tareq Darwish'];
        
        EmailTemplate et = [SELECT Id, Name, Subject, Body FROM EmailTemplate WHERE name = 'Inventory Approval Request'];
        system.debug('et test template '+et);
        for(CD_Approval_Request__c a : lstAprl){
            system.debug('Inside for');
            System.debug('a is'+a);
            System.debug('a.CD App'+a.CD_Approver__c);
            //System.debug('a user is'+a.user);
            string htmlBody = et.Body;
            htmlBody = htmlBody.replace('{!CD_Approval_Request__c.CD_Approver__c}', a.CD_Approver__c);
            htmlBody = htmlBody.replace('{!CD_Approval_Request__c.CD_AgentName_txt__c}',a.CD_AgentName_txt__c);
            htmlBody = htmlBody.replace('{!CD_Approval_Request__c.CD_Property_Name__c}', a.CD_Property_Name__c);
            
            // For Testing
            
            //htmlBody = htmlBody.replace('{!CD_Approval_Request__c.CD_Approver__c}', ur.Name);
            //htmlBody = htmlBody.replace('{!CD_Approval_Request__c.CD_AgentName_txt__c}', ur.Name);
            //htmlBody = htmlBody.replace('{!CD_Approval_Request__c.CD_Property_Name__c}', a.CD_Property_Name__c);
            Messaging.SingleEmailMessage email =  new  Messaging.SingleEmailMessage();
             //email.setToAddresses( new List<String> {'harishraja411@gmail.com'});
            list<String> ToAddress = new list<String>();
            ToAddress.add(a.CD_Approver_Email__c);
            //ToAddress.add(a.CD_Agent_Email__c);
            
            //For Testing
            
            //ToAddress.add('harishraja411@gmail.com');
            //ToAddress.add('sureshmahath@gmail.com');
            email.setToAddresses(ToAddress);
            //email.setToAddresses(new List<String> {CD_Approval_Request__c.CD_Approver_Email__c});
            //email.setWhatId(a.Id);
            system.debug('what id '+a.id);
            email.setTemplateId(et.Id);
            system.debug('set template id' + et.id);
            email.setSubject(et.Subject);
            system.debug('set subject '+et.Subject);
            email.setPlainTextBody(htmlBody);
            system.debug('set platin text body '+htmlBody);
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage> {email});
            
        }
    }
    public void finish(database.BatchableContext bc){
        
    }
}