force-app/main/default/objects/CD_Approval_Request__c/CD_Approval_Request__c.object-meta.xml
<CustomObject>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>CD_Agent_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Approval_Rejection_Action__c.field-meta.xml
<CustomField>
    <fullName>CD_Approval_Rejection_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approval / Rejection Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Blocking_Comments__c.field-meta.xml
<CustomField>
    <fullName>CD_Blocking_Comments__c</fullName>
    <label>Blocking Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>CD_Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <formula>Property__r.CD_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>CD_Property_Name__c</fullName>
    <formula>Property__r.CD_Unit_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Status__c.field-meta.xml
<CustomField>
    <fullName>CD_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>CD_Property__c</referenceTo>
    <relationshipLabel>Approval Requests</relationshipLabel>
    <relationshipName>Approval_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Project__c/CD_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/CD_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/fields/CD_Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>CD_Agent_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Name Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Unit (Agent Name Contact)</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Blocking_Comments__c.field-meta.xml
<CustomField>
    <fullName>CD_Blocking_Comments__c</fullName>
    <label>Blocking Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_isblocked__c.field-meta.xml
<CustomField>
    <fullName>CD_isblocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isblocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <label>Project</label>
    <referenceTo>CD_Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>CD_Unit_Number__c</fullName>
    <label>Unit Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>false</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/CD_Property__c/recordTypes/Property.recordType-meta.xml
<RecordType>
    <fullName>Property</fullName>
    <active>true</active>
    <label>Property</label>
</RecordType>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/gsir_company__c.field-meta.xml
<CustomField>
    <fullName>gsir_company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gulf Sotheby&apos;s</fullName>
            </value>
            <value>
                <fullName>Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Clark &amp; Scott</fullName>
                <isActive>false</isActive>
                <label>Clark &amp; Scott</label>
            </value>
            <value>
                <fullName>External Brokers</fullName>
                <isActive>false</isActive>
                <label>External Brokers</label>
            </value>
            <value>
                <fullName>Internal Brokers</fullName>
                <isActive>false</isActive>
                <label>Internal Brokers</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/test_customApprovalPageCntrlr.cls
@istest
public class test_customApprovalPageCntrlr {
    
     @testSetup static void setupmethod() {
         
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        
        String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+RandomId; 
        User uu=new User(firstname = 'Benedict',  
                         lastName = 'Texeira', 
                         email = 'vijay@gmail.com', 
                         Username = 'Texeira@sfdc.dev', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = uniqueName.substring(18, 23), 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US', 
                         gsir_company__c= 'Gulf Sotheby\'s',
                         ProfileId = pf.Id
                        ); 
        
        
        insert uu;
        
         Profile pf2= [Select Id from profile where Name='System Administrator']; 
        
        String orgId2=UserInfo.getOrganizationId(); 
        String dateString2=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId2=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName2=orgId2+dateString+RandomId2; 
        User uuu=new User(firstname = 'Benedict',  
                         lastName = 'Texeira', 
                         email = 'vijay@gmail.com', 
                         Username = 'Texetestira@sfdc.dev', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = uniqueName2.substring(18, 23), 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US', 
                         gsir_company__c= 'Gulf Sotheby\'s',
                         ProfileId = pf2.Id
                        ); 
        
        
        insert uuu;
        
       
        
    
        List<PermissionSet> PST = [SELECT Id from PermissionSet WHERE IsCustom = True AND LicenseId = Null];
        List<PermissionSetAssignment> PSA = New List<PermissionSetAssignment>();
        for(PermissionSet ps: pst){
            PSA.add(new PermissionSetAssignment(
                AssigneeId = uu.Id,
                PermissionSetId = ps.Id));
           
        }
        insert PSA;
       
        
    }
	@istest
    public static void test_getSubmittedRecords()
    {
        
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name ='Test property';
        prop.CD_Project__c=proj.id;
        prop.CD_isblocked__c= true;
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        
        
        User user1 = [SELECT Id FROM User WHERE UserName='Texeira@sfdc.dev' limit 1];

        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
      req.setComments('Submitting request for approval via form');
      req.setObjectId(prop.Id);
        system.debug('display prop id' +prop.id);
    
     
      //Step 3:  Submit on behalf of a specific submitter
      req.setSubmitterId(UserInfo.getUserId()); 
   
      //Step 4:  Submit the record to specific process and skip the criteria evaluation
      req.setProcessDefinitionNameOrId('CD_Block_Approval');
      req.setSkipEntryCriteria(true);

      //Step 5:  Submit the approval request for the bid
      Approval.ProcessResult result = Approval.process(req);
		
        string processType ='Approve';
        string approverComments = 'Approved';
        
      

      //  Integer intvar = MultiRecordsApprovalController.gettotalcount();
     // List<customApprovalPageCntrlr.SubmittedRecordsWrapper> prorec = new List<customApprovalPageCntrlr.SubmittedRecordsWrapper>();
       // 	customApprovalPageCntrlr.getSubmittedRecords();
        customApprovalPageCntrlr.processApproval(prop.id,processType,approverComments);
       
    }
    
    @istest
     
    public static void test_sumbittedRec()
    {
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name ='Test property';
        prop.CD_Project__c=proj.id;
        prop.CD_isblocked__c= true;
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
         CD_Approval_Request__c aprReq = new CD_Approval_Request__c();
        	aprReq.CD_Expiry_Date__c = system.today() +3;
        	aprReq.CD_Blocking_Comments__c ='test comment';
        aprReq.CD_Status__c ='Declined';
        aprReq.CD_Approval_Rejection_Action__c = true;
        	aprReq.Property__c= prop.Id;
        insert aprReq;
        
        
        User user1 = [SELECT Id FROM User WHERE UserName='Texeira@sfdc.dev' limit 1];

        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
      req.setComments('Submitting request for approval via form');
      req.setObjectId(aprReq.Id);
       //system.debug('display prop id' +prop.id);
    
     
      //Step 3:  Submit on behalf of a specific submitter
      req.setSubmitterId(UserInfo.getUserId()); 
   
      //Step 4:  Submit the record to specific process and skip the criteria evaluation
      req.setProcessDefinitionNameOrId('Test_class_Approval');
      req.setSkipEntryCriteria(true);

      //Step 5:  Submit the approval request for the bid
      Approval.ProcessResult result = Approval.process(req);
		
        string processType ='Approve';
        string approverComments = 'Approved';
        List<customApprovalPageCntrlr.SubmittedRecordsWrapper> prorec = new List<customApprovalPageCntrlr.SubmittedRecordsWrapper>();
        customApprovalPageCntrlr.getSubmittedRecords();
         
    }
    
    
    @istest
    
    public static void test_createApprovalRequestRec()
    {
         CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name ='Test property';
        prop.CD_Project__c=proj.id;
        prop.CD_isblocked__c= true;
        prop.CD_Unit_Number__c ='Test property';
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
         User user1 = [SELECT Id FROM User WHERE UserName='Texeira@sfdc.dev' limit 1];
         CD_Approval_Request__c aprReq = new CD_Approval_Request__c();
        	aprReq.CD_Expiry_Date__c = system.today() +3;
        	aprReq.CD_Blocking_Comments__c ='test comment';
        	aprReq.CD_Status__c ='Pending';
        	aprReq.Property__c= prop.Id;
        aprReq.CD_Agent_Name__c =user1.id;
       // aprReq.CD_Property_Name__c=
        insert aprReq;
        string appcom ='Test approver comment';
        date expdate = system.today() +5;
        string status ='Approved';
        date finaDate = system.Today()+1;
        customApprovalPageCntrlr.createApprovalRequestRec(prop.id,appcom,expDate);
        customApprovalPageCntrlr.fetchApprovalRequest(prop.id);
        customApprovalPageCntrlr.getAgentSumbittedApprvRec();
        customApprovalPageCntrlr.updateApprovalReq(prop.id,appcom,status,finaDate);
        
    }
}