force-app/main/default/objects/CD_Approval_Request__c/CD_Approval_Request__c.object-meta.xml
<CustomObject>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>CD_Agent_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Block_Date__c.field-meta.xml
<CustomField>
    <fullName>CD_Block_Date__c</fullName>
    <label>Block Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Blocking_Comments__c.field-meta.xml
<CustomField>
    <fullName>CD_Blocking_Comments__c</fullName>
    <label>Blocking Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>CD_Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <formula>Property__r.CD_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/CD_Status__c.field-meta.xml
<CustomField>
    <fullName>CD_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/Project_Approver__c.field-meta.xml
<CustomField>
    <fullName>Project_Approver__c</fullName>
    <formula>IF(Property__r.Property_Approver__r.Id == $User.Id,True,False)</formula>
    <label>Project Approver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CD_Approval_Request__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>CD_Property__c</referenceTo>
    <relationshipLabel>Approval Requests</relationshipLabel>
    <relationshipName>Approval_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Project__c/CD_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Project__c/fields/Project_Approver__c.field-meta.xml
<CustomField>
    <fullName>Project_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/CD_Property__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CD_Property__c/fields/CD_Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>CD_Agent_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Name Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Unit (Agent Name Contact)</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Agent_Name_User__c.field-meta.xml
<CustomField>
    <fullName>CD_Agent_Name_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Properties1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Agent_Representing_Client__c.field-meta.xml
<CustomField>
    <fullName>CD_Agent_Representing_Client__c</fullName>
    <label>Agent Representing Client</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Block_Comments__c.field-meta.xml
<CustomField>
    <fullName>CD_Block_Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Block_Date__c.field-meta.xml
<CustomField>
    <fullName>CD_Block_Date__c</fullName>
    <label>Block Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Blocking_Comments__c.field-meta.xml
<CustomField>
    <fullName>CD_Blocking_Comments__c</fullName>
    <label>Blocking Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Brokerage_Representing_Client__c.field-meta.xml
<CustomField>
    <fullName>CD_Brokerage_Representing_Client__c</fullName>
    <label>Brokerage Representing Client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>CD_Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personal Cheque</fullName>
            </value>
            <value>
                <fullName>Managers Cheque</fullName>
            </value>
            <value>
                <fullName>Third Party Payment</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Not Yet Confirmed</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
            <value>
                <fullName>Credit/Debit Card</fullName>
                <isActive>false</isActive>
                <label>Credit/Debit Card</label>
            </value>
            <value>
                <fullName>Net Banking</fullName>
                <isActive>false</isActive>
                <label>Net Banking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Payment_Percentage__c.field-meta.xml
<CustomField>
    <fullName>CD_Payment_Percentage__c</fullName>
    <label>Payment Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Project__c.field-meta.xml
<CustomField>
    <fullName>CD_Project__c</fullName>
    <label>Project</label>
    <referenceTo>CD_Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Purchase_date__c.field-meta.xml
<CustomField>
    <fullName>CD_Purchase_date__c</fullName>
    <label>Purchase date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Second_Agent__c.field-meta.xml
<CustomField>
    <fullName>CD_Second_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Second Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Properties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_Units__c.field-meta.xml
<CustomField>
    <fullName>CD_Units__c</fullName>
    <label>Units</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/CD_View__c.field-meta.xml
<CustomField>
    <fullName>CD_View__c</fullName>
    <label>View</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1-bed Type A</fullName>
            </value>
            <value>
                <fullName>1-bed Type B</fullName>
            </value>
            <value>
                <fullName>2-bed Duplex Type 2A</fullName>
            </value>
            <value>
                <fullName>2-bed Duplex Type 2B</fullName>
            </value>
            <value>
                <fullName>2-bed Duplex Type 2C</fullName>
            </value>
            <value>
                <fullName>2-bed Duplex Type 2D</fullName>
            </value>
            <value>
                <fullName>2-bed Type A</fullName>
            </value>
            <value>
                <fullName>2-bed Type B</fullName>
            </value>
            <value>
                <fullName>2-bed Type C</fullName>
            </value>
            <value>
                <fullName>2-bed Type D</fullName>
            </value>
            <value>
                <fullName>2-bed Type E</fullName>
            </value>
            <value>
                <fullName>2-bed Type F</fullName>
            </value>
            <value>
                <fullName>2-bed Type H</fullName>
            </value>
            <value>
                <fullName>2-bed Type J</fullName>
            </value>
            <value>
                <fullName>3-bed Duplex Type 3A</fullName>
            </value>
            <value>
                <fullName>3-bed Type A</fullName>
            </value>
            <value>
                <fullName>3-bed Type B</fullName>
            </value>
            <value>
                <fullName>3-bed Type C</fullName>
            </value>
            <value>
                <fullName>3-bed Type D</fullName>
            </value>
            <value>
                <fullName>3-bed Type E</fullName>
            </value>
            <value>
                <fullName>4-bed Duplex Type 4A</fullName>
            </value>
            <value>
                <fullName>4-bed Duplex Type 4B</fullName>
            </value>
            <value>
                <fullName>ADGM SQUARE</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf / DIFC Burj Khalifa</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf / The Dubai Frame</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf / The Dubai Frame / Zaabeel</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf &amp; Burj Khalifa</fullName>
            </value>
            <value>
                <fullName>Arabian Gulf &amp; The Dubai Frame</fullName>
            </value>
            <value>
                <fullName>Beach</fullName>
            </value>
            <value>
                <fullName>Park</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/Project_Approver__c.field-meta.xml
<CustomField>
    <fullName>Project_Approver__c</fullName>
    <formula>CD_Project__r.Project_Approver__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Approver</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CD_Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Red Listed Review</fullName>
            </value>
            <value>
                <fullName>Red Listed</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CD_Property__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>false</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/CD_Property__c/recordTypes/Property.recordType-meta.xml
<RecordType>
    <fullName>Property</fullName>
    <active>true</active>
    <label>Property</label>
</RecordType>

force-app/main/default/objects/User/fields/gsir_company__c.field-meta.xml
<CustomField>
    <fullName>gsir_company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gulf Sotheby&apos;s</fullName>
            </value>
            <value>
                <fullName>Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Clark &amp; Scott</fullName>
                <isActive>false</isActive>
                <label>Clark &amp; Scott</label>
            </value>
            <value>
                <fullName>External Brokers</fullName>
                <isActive>false</isActive>
                <label>External Brokers</label>
            </value>
            <value>
                <fullName>Internal Brokers</fullName>
                <isActive>false</isActive>
                <label>Internal Brokers</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_ManagePropertyCntrlr.cls
@istest
public class Test_ManagePropertyCntrlr {
    
    
    @testSetup static void setupmethod() {
        
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        
        String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+RandomId; 
        User uu=new User(firstname = 'Benedict',  
                         lastName = 'Texeira', 
                         email = 'vijay@gmail.com', 
                         Username = 'Texeira@sfdc.dev', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = uniqueName.substring(18, 23), 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US', 
                         gsir_company__c= 'Gulf Sotheby\'s',
                         ProfileId = pf.Id
                        ); 
        
        
        insert uu;
        Profile pf1= [Select Id from profile where Name='PB Agent']; 
        
        String orgId1=UserInfo.getOrganizationId(); 
        String dateString1=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId1=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName1=orgId+dateString+RandomId; 
        User uuu=new User(firstname = 'Benedict',  
                          lastName = 'Texeirerra', 
                          email = 'vijay@gmail.com', 
                          Username = 'Texeira@sfdryyc.dev', 
                          EmailEncodingKey = 'ISO-8859-1', 
                          Alias = uniqueName.substring(18, 23), 
                          TimeZoneSidKey = 'America/Los_Angeles', 
                          LocaleSidKey = 'en_US', 
                          LanguageLocaleKey = 'en_US', 
                          gsir_company__c= 'Gulf Sotheby\'s',
                          ProfileId = pf1.Id
                         ); 
        
        
        insert uuu;
        
        Profile pf2= [Select Id from profile where Name= 'Development Projects']; 
        
        String orgId2=UserInfo.getOrganizationId(); 
        String dateString2=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId2=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName2=orgId2+dateString2+RandomId2; 
        User uuuu=new User(firstname = 'Ben',  
                          lastName = 'Tex', 
                          email = 'vijaya@gmail.com', 
                          Username = 'Tex@sfdryyc.dev', 
                          EmailEncodingKey = 'ISO-8859-1', 
                          Alias = uniqueName.substring(18, 23), 
                          TimeZoneSidKey = 'America/Los_Angeles', 
                          LocaleSidKey = 'en_US', 
                          LanguageLocaleKey = 'en_US', 
                          gsir_company__c= 'Gulf Sotheby\'s',
                          ProfileId = pf2.Id
                         ); 
        
        
        insert uuuu;
        
    }
    
    @istest
    public static void test_updateProperty()
    {
        User user1 = [SELECT Id FROM User WHERE UserName='Texeira@sfdc.dev' limit 1];
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        proj.Project_Approver__c = user1.Id;
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name ='Test property';
        prop.CD_Project__c=proj.id;
        prop.CD_Agent_Name_User__c=user1.id;
        prop.CD_Block_Comments__c ='Test comments';
        prop.CD_Block_Date__c = system.today();
        prop.CD_Units__c= 5;
        prop.CD_Payment_Percentage__c = 20;
        prop.CD_Mode_of_Payment__c ='Bank Transfer';
        prop.CD_Purchase_date__c =system.today();
        prop.CD_Agent_Representing_Client__c = 'Test agent';
        prop.CD_Brokerage_Representing_Client__c ='test brokerage';
        prop.CD_Second_Agent__c =user1.id;
        
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        
        
        CD_Approval_Request__c aprReq = new CD_Approval_Request__c();
        aprReq.CD_Expiry_Date__c = system.today() +3;
        aprReq.CD_Blocking_Comments__c ='test comment';
        aprReq.CD_Status__c ='Pending';
        aprReq.Property__c= prop.Id;
        aprReq.CD_Agent_Name__c =prop.CD_Agent_Name_User__c;
        insert aprReq;
        //	string propId = prop.id;
        cd_Property__c testProp =[select id,name,CD_Agent_Representing_Client__c,CD_Agent_Name_User__c,CD_Purchase_date__c ,CD_Payment_Percentage__c,CD_Mode_of_Payment__c,CD_Block_Comments__c,CD_Block_Date__c,CD_Units__c from cd_Property__c limit 1];
        ManagePropertyCntrlr.updateProperty(prop.id,testProp);
        // managePropertyCls.updateProperty(propId,testProp);
        
    }
    
    @istest
    public static void test_getProperty()
    {
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name ='Test property';
        prop.CD_Project__c=proj.id;
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        
        cd_Property__c testProp =[select id,name from cd_Property__c limit 1];
        integer pagesize = 10;
        integer pagenumber = 1;
        
        ManagePropertyCntrlr.getProperty(pagesize,pagenumber,'CD_View__c','ASC');
        ManagePropertyCntrlr.getProperty(pagesize,pagenumber,NULL,NULL);
        ManagePropertyCntrlr.getAgentProperty(pagesize,pagenumber,'CD_View__c','ASC');
        ManagePropertyCntrlr.getAgentProperty(pagesize,pagenumber,NULL,NULL);
        
        //system.assertEquals('Test property',testProp.Name);
    }
    
    @istest
    public static void test_getAgentProperty()
    {
        user u1 =[select id from user where Username = 'Texeira@sfdryyc.dev'];
        system.runAs(u1)
        {
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name ='Test property';
        prop.CD_Project__c=proj.id;
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        
        cd_Property__c testProp =[select id,name from cd_Property__c limit 1];
        integer pagesize = 10;
        integer pagenumber = 1;
        
        ManagePropertyCntrlr.getProperty(pagesize,pagenumber,'CD_View__c','ASC');
        ManagePropertyCntrlr.getProperty(pagesize,pagenumber,NULL,NULL);
        ManagePropertyCntrlr.getAgentProperty(pagesize,pagenumber,'CD_View__c','ASC');
        ManagePropertyCntrlr.getAgentProperty(pagesize,pagenumber,NULL,NULL);
        
        //system.assertEquals('Test property',testProp.Name);
        }
    }
    @istest 
    public static void test_selectedProject()
    {
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        string varProj = 'Test Project';
        ManagePropertyCntrlr.selectedProject(varProj);
        // managePropertyCls.getProjectSelected(varProj);
        ManagePropertyCntrlr.getProject(); 
    }
    
    @istest
    public static void test_getProjectSelected()
    {
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        string varProj = 'Test';
        ManagePropertyCntrlr.getProjectSelected(varProj);
    }
    
    @istest
    public static void test_dynamicalResult()
    {
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name ='Test property';
        prop.CD_Project__c=proj.id;
        prop.Type__c ='Condo';
        prop.Status__c ='Available';
        prop.City_Dubizzle__c ='Dubai';
        prop.CD_Bedrooms__c = '2BR';
        prop.CD_View__c = 'Park';
        prop.Floor_Type__c = 'High Floor';
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        
        string getType = 'condo';
        string getCity ='Dubai';
        string getStatus ='Available';
        String noOfBed = '2BR';
        string projName ='Wasl';
        string propView = 'Park';
        string propFloorType = 'High Floor';
        string propTower = 'Tower';
        
        
        string empstat =null;
        string empbed = null;
        string empproj = null;
        string empView = null;
        string empFloor = null;
        string empUnitS = null;
        string empTower = null;
        
        integer pagesize = 10;
        integer pagenumber = 1;
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,noOfBed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,noOfBed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
        
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,empbed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
        // ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,projName,empView,empFloor,empUnitS,empTower);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,noOfBed,empproj,empView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,empbed,empproj,empView,empFloor,empUnitS,empTower,NULL,NULL);
            
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,empView,empFloor,empUnitS,empTower,NULL,NULL);
        
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,noOfBed,empproj,propView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,propView,empFloor,empUnitS,empTower,'CD_View__c','ASC');
        
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,empView,propFloorType,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,empView,propFloorType,'01',empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,noOfBed,empproj,empView,propFloorType,empUnitS,propTower,NULL,NULL);
        
    }
    @istest
    public static void test_dynamicalAgentResult()
    {
        user u1 =[select id from user where Username = 'Texeira@sfdryyc.dev'];
        system.runAs(u1)
        {
            CD_Project__c proj = new CD_Project__c();
            proj.Name = 'Test Project';
            insert proj;
            
            cd_Property__c prop = new cd_Property__c();
            prop.Name ='Test property';
            prop.CD_Project__c=proj.id;
            prop.Type__c ='Condo';
            prop.Status__c ='Available';
            prop.City_Dubizzle__c ='Dubai';
            prop.CD_Bedrooms__c = '2BR';
            prop.CD_View__c = 'Park';
            prop.Floor_Type__c = 'High Floor';
            prop.CD_Tower__c = 'Tower';
            
            list<cd_Property__c> propList = new list <cd_Property__c>();
            propList.add(prop);
            insert propList;
            
            string getType = 'condo';
            string getCity ='Dubai';
            string getStatus ='Available';
            String noOfBed = '2BR';
            string projName ='Wasl';
            string propView = 'Park';
            string propFloorType = 'High Floor';
            string propTower = 'Tower';
            
            
            string empstat =null;
            string empbed = null;
            string empproj = null;
            string empView = null;
            string empFloor = null;
            string empUnitS = null;
            string empTower = null;
            
            integer pagesize = 10;
            integer pagenumber = 1;
            ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,noOfBed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,empbed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
        // ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,projName,empView,empFloor,empUnitS,empTower);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,noOfBed,empproj,empView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,empbed,empproj,empView,empFloor,empUnitS,empTower,NULL,NULL);
         ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,noOfBed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
           
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,empView,empFloor,empUnitS,empTower,NULL,NULL);
        
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,noOfBed,empproj,propView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,propView,empFloor,empUnitS,empTower,'CD_View__c','ASC');
        
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,empView,propFloorType,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,empView,propFloorType,'01',empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,noOfBed,empproj,empView,propFloorType,empUnitS,propTower,NULL,NULL);
        
        }   
        
    }
    
    @istest
    public static void test_dynamicalAgentResult2()
    {
        user u1 =[select id from user where Username = 'Tex@sfdryyc.dev'];
        system.runAs(u1)
        {
            CD_Project__c proj = new CD_Project__c();
            proj.Name = 'Test Project';
            insert proj;
            
            cd_Property__c prop = new cd_Property__c();
            prop.Name ='Test property';
            prop.CD_Project__c=proj.id;
            prop.Type__c ='Condo';
            prop.Status__c ='Available';
            prop.City_Dubizzle__c ='Dubai';
            prop.CD_Bedrooms__c = '2BR';
            prop.CD_View__c = 'Park';
            prop.Floor_Type__c = 'High Floor';
            prop.CD_Tower__c = 'Tower';
            
            list<cd_Property__c> propList = new list <cd_Property__c>();
            propList.add(prop);
            insert propList;
            
            string getType = 'condo';
            string getCity ='Dubai';
            string getStatus ='Available';
            String noOfBed = '2BR';
            string projName ='Wasl';
            string propView = 'Park';
            string propFloorType = 'High Floor';
            string propTower = 'Tower';
            
            
            string empstat =null;
            string empbed = null;
            string empproj = null;
            string empView = null;
            string empFloor = null;
            string empUnitS = null;
            string empTower = null;
            
            integer pagesize = 10;
            integer pagenumber = 1;
            ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,noOfBed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,empbed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
        // ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,projName,empView,empFloor,empUnitS,empTower);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,noOfBed,empproj,empView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,empbed,empproj,empView,empFloor,empUnitS,empTower,NULL,NULL);
         ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,noOfBed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,projName,empView,empFloor,empUnitS,empTower,NULL,NULL);
           
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,empView,empFloor,empUnitS,empTower,NULL,NULL);
        
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,getStatus,noOfBed,empproj,propView,empFloor,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,propView,empFloor,empUnitS,empTower,'CD_View__c','ASC');
        
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,empView,propFloorType,empUnitS,empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,empbed,empproj,empView,propFloorType,'01',empTower,NULL,NULL);
        ManagePropertyCntrlr.dynamicalResult(pagesize,pagenumber,empstat,noOfBed,empproj,empView,propFloorType,empUnitS,propTower,NULL,NULL);
        
        }   
        
    }
    @istest
    public static void test_searchResults()
    {
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name ='Test property';
        prop.CD_Project__c=proj.id;
        prop.Type__c ='Condo';
        prop.Status__c ='Available';
        prop.City_Dubizzle__c ='Dubai';
        prop.CD_Tower__c = 'West';
        
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        
        string searchVar = 'condo';
        string searchTower = 'West';
        string searchUS = '01';
        string projName = proj.Name;
        ManagePropertyCntrlr.searchResults(searchVar,NULL,NUll,projName);
        
    }
    @istest
    public static void test_setObjectToRecentItems()
    {
        
        CD_Project__c proj = new CD_Project__c();
        proj.Name = 'Test Project';
        insert proj;
        
        cd_Property__c prop = new cd_Property__c();
        prop.Name ='Test property';
        prop.CD_Project__c=proj.id;
        prop.Type__c ='Condo';
        prop.Status__c ='Available';
        prop.City_Dubizzle__c ='Dubai';
        list<cd_Property__c> propList = new list <cd_Property__c>();
        propList.add(prop);
        insert propList;
        ManagePropertyCntrlr.setObjectToRecentItems(prop.id);
        
    }
}