force-app/main/default/objects/Closing_Commission__c/Closing_Commission__c.object-meta.xml
<CustomObject>
    <label>Closing Commission</label>
    <nameField>
        <displayFormat>CC -{0000}</displayFormat>
        <label>Closing Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Commission</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Closing_Commission__c/fields/Agent_Type__c.field-meta.xml
<CustomField>
    <fullName>Agent_Type__c</fullName>
    <label>Internal Agent Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusive Broker</fullName>
            </value>
            <value>
                <fullName>Resale Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Closing_Commission__c/fields/Closing__c.field-meta.xml
<CustomField>
    <fullName>Closing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closing</label>
    <referenceTo>pba__Closing__c</referenceTo>
    <relationshipLabel>Closing Commission</relationshipLabel>
    <relationshipName>Closing_Commission</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Closing_Commission__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Closing_Commission__c/fields/Lux_Agent__c.field-meta.xml
<CustomField>
    <fullName>Lux_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Closing_Commission</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClosingCommisionTestClass.cls
@isTest
private class ClosingCommisionTestClass {
    @isTest static void TestInsertClosingShareOnClosingCommission() {
        pba__Closing__c obj = new pba__Closing__c();
        obj.TargetClosingDate__c = system.today() + 4;
        insert obj;
        List<User> userList = [Select Id from user where Profile.Name = 'DP_AGENT' And IsActive= True limit 2];
        // Test data setup
        test.startTest();
        Closing_Commission__c ccom = new Closing_Commission__c();
        ccom.Lux_Agent__c = userList[0].Id;
        ccom.Closing__c = obj.Id;
        ccom.Commission_Amount__c = 110;
        ccom.Agent_Type__c = 'Resale Broker';
      //  ccom.User_Division__c ='Resale';
        insert ccom;
        ccom.OwnerId = userList[1].Id;
        update ccom;
        delete ccom;
        test.stopTest();
    }
}